// ISO 3166-2 subdivisions for countries in Africa (continent code: AF)
export const AFRICA_REGIONS: Record<string, string> = {
  "DZ-01": "Adrar",
  "DZ-44": "Aïn Defla",
  "DZ-46": "Aïn Témouchent",
  "DZ-16": "Alger",
  "DZ-23": "Annaba",
  "DZ-05": "Batna",
  "DZ-08": "Béchar",
  "DZ-06": "Béjaïa",
  "DZ-52": "Béni Abbès",
  "DZ-07": "Biskra",
  "DZ-09": "Blida",
  "DZ-50": "Bordj Badji Mokhtar",
  "DZ-34": "Bordj Bou Arréridj",
  "DZ-10": "Bouira",
  "DZ-35": "Boumerdès",
  "DZ-02": "Chlef",
  "DZ-25": "Constantine",
  "DZ-56": "Djanet",
  "DZ-17": "Djelfa",
  "DZ-32": "El Bayadh",
  "DZ-57": "El Meghaier",
  "DZ-58": "El Meniaa",
  "DZ-39": "El Oued",
  "DZ-36": "El Tarf",
  "DZ-47": "Ghardaïa",
  "DZ-24": "Guelma",
  "DZ-33": "Illizi",
  "DZ-54": "In Guezzam",
  "DZ-53": "In Salah",
  "DZ-18": "Jijel",
  "DZ-40": "Khenchela",
  "DZ-03": "Laghouat",
  "DZ-28": "M'sila",
  "DZ-29": "Mascara",
  "DZ-26": "Médéa",
  "DZ-43": "Mila",
  "DZ-27": "Mostaganem",
  "DZ-45": "Naama",
  "DZ-31": "Oran",
  "DZ-30": "Ouargla",
  "DZ-51": "Ouled Djellal",
  "DZ-04": "Oum el Bouaghi",
  "DZ-48": "Relizane",
  "DZ-20": "Saïda",
  "DZ-19": "Sétif",
  "DZ-22": "Sidi Bel Abbès",
  "DZ-21": "Skikda",
  "DZ-41": "Souk Ahras",
  "DZ-11": "Tamanrasset",
  "DZ-12": "Tébessa",
  "DZ-14": "Tiaret",
  "DZ-49": "Timimoun",
  "DZ-37": "Tindouf",
  "DZ-42": "Tipaza",
  "DZ-38": "Tissemsilt",
  "DZ-15": "Tizi Ouzou",
  "DZ-13": "Tlemcen",
  "DZ-55": "Touggourt",
  "AO-BGO": "Bengo",
  "AO-BGU": "Benguela",
  "AO-BIE": "Bié",
  "AO-CAB": "Cabinda",
  "AO-CCU": "Cuando Cubango",
  "AO-CNO": "Cuanza-Norte",
  "AO-CUS": "Cuanza-Sul",
  "AO-CNN": "Cunene",
  "AO-HUA": "Huambo",
  "AO-HUI": "Huíla",
  "AO-LUA": "Luanda",
  "AO-LNO": "Lunda-Norte",
  "AO-LSU": "Lunda-Sul",
  "AO-MAL": "Malange",
  "AO-MOX": "Moxico",
  "AO-NAM": "Namibe",
  "AO-UIG": "Uíge",
  "AO-ZAI": "Zaire",
  "BJ-AL": "Alibori",
  "BJ-AK": "Atacora",
  "BJ-AQ": "Atlantique",
  "BJ-BO": "Borgou",
  "BJ-CO": "Collines",
  "BJ-KO": "Couffo",
  "BJ-DO": "Donga",
  "BJ-LI": "Littoral",
  "BJ-MO": "Mono",
  "BJ-OU": "Ouémé",
  "BJ-PL": "Plateau",
  "BJ-ZO": "Zou",
  "BW-CE": "Central",
  "BW-CH": "Chobe",
  "BW-FR": "Francistown",
  "BW-GA": "Gaborone",
  "BW-GH": "Ghanzi",
  "BW-JW": "Jwaneng",
  "BW-KG": "Kgalagadi",
  "BW-KL": "Kgatleng",
  "BW-KW": "Kweneng",
  "BW-LO": "Lobatse",
  "BW-NE": "North East",
  "BW-NW": "North West",
  "BW-SP": "Selibe Phikwe",
  "BW-SE": "South East",
  "BW-SO": "Southern",
  "BW-ST": "Sowa Town",
  "BF-01": "Boucle du Mouhoun",
  "BF-02": "Cascades",
  "BF-03": "Centre",
  "BF-04": "Centre-Est",
  "BF-05": "Centre-Nord",
  "BF-06": "Centre-Ouest",
  "BF-07": "Centre-Sud",
  "BF-08": "Est",
  "BF-09": "Hauts-Bassins",
  "BF-10": "Nord",
  "BF-11": "Plateau-Central",
  "BF-12": "Sahel",
  "BF-13": "Sud-Ouest",
  "BI-BB": "Bubanza",
  "BI-BM": "Bujumbura Mairie",
  "BI-BL": "Bujumbura Rural",
  "BI-BR": "Bururi",
  "BI-CA": "Cankuzo",
  "BI-CI": "Cibitoke",
  "BI-GI": "Gitega",
  "BI-KR": "Karuzi",
  "BI-KY": "Kayanza",
  "BI-KI": "Kirundo",
  "BI-MA": "Makamba",
  "BI-MU": "Muramvya",
  "BI-MY": "Muyinga",
  "BI-MW": "Mwaro",
  "BI-NG": "Ngozi",
  "BI-RM": "Rumonge",
  "BI-RT": "Rutana",
  "BI-RY": "Ruyigi",
  "CM-AD": "Adamaoua",
  "CM-CE": "Centre",
  "CM-ES": "East",
  "CM-EN": "Far North",
  "CM-LT": "Littoral",
  "CM-NO": "North",
  "CM-NW": "North-West",
  "CM-SU": "South",
  "CM-SW": "South-West",
  "CM-OU": "West",
  "CV-B": "Ilhas de Barlavento",
  "CV-S": "Ilhas de Sotavento",
  "CF-BB": "Bamingui-Bangoran",
  "CF-BGF": "Bangui",
  "CF-BK": "Basse-Kotto",
  "CF-KB": "Gribingui",
  "CF-HM": "Haut-Mbomou",
  "CF-HK": "Haute-Kotto",
  "CF-HS": "Haute-Sangha / Mambéré-Kadéï",
  "CF-KG": "Kémo-Gribingui",
  "CF-LB": "Lobaye",
  "CF-MB": "Mbomou",
  "CF-NM": "Nana-Mambéré",
  "CF-MP": "Ombella-Mpoko",
  "CF-UK": "Ouaka",
  "CF-AC": "Ouham",
  "CF-OP": "Ouham-Pendé",
  "CF-SE": "Sangha",
  "CF-VK": "Vakaga",
  "TD-BG": "Baḩr al Ghazāl",
  "TD-BA": "Al Baţḩā’",
  "TD-BO": "Būrkū",
  "TD-CB": "Shārī Bāqirmī",
  "TD-EE": "Inīdī ash Sharqī",
  "TD-EO": "Inīdī al Gharbī",
  "TD-GR": "Qīrā",
  "TD-HL": "Ḩajjar Lamīs",
  "TD-KA": "Kānim",
  "TD-LC": "Al Buḩayrah",
  "TD-LO": "Lūghūn al Gharbī",
  "TD-LR": "Lūghūn ash Sharqī",
  "TD-MA": "Māndūl",
  "TD-ME": "Māyū Kībbī ash Sharqī",
  "TD-MO": "Māyū Kībbī al Gharbī",
  "TD-MC": "Shārī al Awsaţ",
  "TD-OD": "Waddāy",
  "TD-SA": "Salāmāt",
  "TD-SI": "Sīlā",
  "TD-TA": "Tānjīlī",
  "TD-TI": "Tibastī",
  "TD-ND": "Madīnat Injamīnā",
  "TD-WF": "Wādī Fīrā’",
  "KM-G": "Grande Comore",
  "KM-A": "Anjouan",
  "KM-M": "Mohéli",
  "CG-11": "Bouenza",
  "CG-BZV": "Brazzaville",
  "CG-8": "Cuvette",
  "CG-15": "Cuvette-Ouest",
  "CG-5": "Kouilou",
  "CG-2": "Lékoumou",
  "CG-7": "Likouala",
  "CG-9": "Niari",
  "CG-14": "Plateaux",
  "CG-16": "Pointe-Noire",
  "CG-12": "Pool",
  "CG-13": "Sangha",
  "CD-BU": "Bas-Uélé",
  "CD-EQ": "Équateur",
  "CD-HK": "Haut-Katanga",
  "CD-HL": "Haut-Lomami",
  "CD-HU": "Haut-Uélé",
  "CD-IT": "Ituri",
  "CD-KS": "Kasaï",
  "CD-KC": "Kasaï Central",
  "CD-KE": "Kasaï Oriental",
  "CD-KN": "Kinshasa",
  "CD-BC": "Kongo Central",
  "CD-KG": "Kwango",
  "CD-KL": "Kwilu",
  "CD-LO": "Lomami",
  "CD-LU": "Lualaba",
  "CD-MN": "Mai-Ndombe",
  "CD-MA": "Maniema",
  "CD-MO": "Mongala",
  "CD-NK": "Nord-Kivu",
  "CD-NU": "Nord-Ubangi",
  "CD-SA": "Sankuru",
  "CD-SK": "Sud-Kivu",
  "CD-SU": "Sud-Ubangi",
  "CD-TA": "Tanganyika",
  "CD-TO": "Tshopo",
  "CD-TU": "Tshuapa",
  "CI-AB": "Abidjan",
  "CI-BS": "Bas-Sassandra",
  "CI-CM": "Comoé",
  "CI-DN": "Denguélé",
  "CI-GD": "Gôh-Djiboua",
  "CI-LC": "Lacs",
  "CI-LG": "Lagunes",
  "CI-MG": "Montagnes",
  "CI-SM": "Sassandra-Marahoué",
  "CI-SV": "Savanes",
  "CI-VB": "Vallée du Bandama",
  "CI-WR": "Woroba",
  "CI-YM": "Yamoussoukro",
  "CI-ZZ": "Zanzan",
  "DJ-AS": "Ali Sabieh",
  "DJ-AR": "Arta",
  "DJ-DI": "Dikhil",
  "DJ-DJ": "Djibouti",
  "DJ-OB": "Obock",
  "DJ-TA": "Tadjourah",
  "EG-DK": "Ad Daqahlīyah",
  "EG-BA": "Al Baḩr al Aḩmar",
  "EG-BH": "Al Buḩayrah",
  "EG-FYM": "Al Fayyūm",
  "EG-GH": "Al Gharbīyah",
  "EG-ALX": "Al Iskandarīyah",
  "EG-IS": "Al Ismā'īlīyah",
  "EG-GZ": "Al Jīzah",
  "EG-MNF": "Al Minūfīyah",
  "EG-MN": "Al Minyā",
  "EG-C": "Al Qāhirah",
  "EG-KB": "Al Qalyūbīyah",
  "EG-LX": "Al Uqşur",
  "EG-WAD": "Al Wādī al Jadīd",
  "EG-SUZ": "As Suways",
  "EG-SHR": "Ash Sharqīyah",
  "EG-ASN": "Aswān",
  "EG-AST": "Asyūţ",
  "EG-BNS": "Banī Suwayf",
  "EG-PTS": "Būr Sa‘īd",
  "EG-DT": "Dumyāţ",
  "EG-JS": "Janūb Sīnā'",
  "EG-KFS": "Kafr ash Shaykh",
  "EG-MT": "Maţrūḩ",
  "EG-KN": "Qinā",
  "EG-SIN": "Shamāl Sīnā'",
  "EG-SHG": "Sūhāj",
  "GQ-C": "Región Continental",
  "GQ-I": "Región Insular",
  "ER-MA": "Al Awsaţ",
  "ER-DU": "Al Janūbī",
  "ER-AN": "Ansabā",
  "ER-DK": "Janūbī al Baḩrī al Aḩmar",
  "ER-GB": "Qāsh-Barkah",
  "ER-SK": "Shimālī al Baḩrī al Aḩmar",
  "ET-AA": "Ādīs Ābeba",
  "ET-AF": "Āfar",
  "ET-AM": "Āmara",
  "ET-BE": "Bīnshangul Gumuz",
  "ET-DD": "Dirē Dawa",
  "ET-GA": "Gambēla Hizboch",
  "ET-HA": "Hārerī Hizb",
  "ET-OR": "Oromīya",
  "ET-SI": "Sīdama",
  "ET-SO": "Sumalē",
  "ET-TI": "Tigray",
  "ET-SN": "YeDebub Bihēroch Bihēreseboch na Hizboch",
  "ET-SW": "YeDebub M‘irab Ītyop’iya Hizboch",
  "GA-1": "Estuaire",
  "GA-2": "Haut-Ogooué",
  "GA-3": "Moyen-Ogooué",
  "GA-4": "Ngounié",
  "GA-5": "Nyanga",
  "GA-6": "Ogooué-Ivindo",
  "GA-7": "Ogooué-Lolo",
  "GA-8": "Ogooué-Maritime",
  "GA-9": "Woleu-Ntem",
  "GM-B": "Banjul",
  "GM-M": "Central River",
  "GM-L": "Lower River",
  "GM-N": "North Bank",
  "GM-U": "Upper River",
  "GM-W": "Western",
  "GH-AF": "Ahafo",
  "GH-AH": "Ashanti",
  "GH-BO": "Bono",
  "GH-BE": "Bono East",
  "GH-CP": "Central",
  "GH-EP": "Eastern",
  "GH-AA": "Greater Accra",
  "GH-NE": "North East",
  "GH-NP": "Northern",
  "GH-OT": "Oti",
  "GH-SV": "Savannah",
  "GH-UE": "Upper East",
  "GH-UW": "Upper West",
  "GH-TV": "Volta",
  "GH-WP": "Western",
  "GH-WN": "Western North",
  "GN-B": "Boké",
  "GN-F": "Faranah",
  "GN-K": "Kankan",
  "GN-D": "Kindia",
  "GN-L": "Labé",
  "GN-M": "Mamou",
  "GN-N": "Nzérékoré",
  "GN-C": "Conakry",
  "GW-L": "Leste",
  "GW-N": "Norte",
  "GW-S": "Sul",
  "KE-01": "Baringo",
  "KE-02": "Bomet",
  "KE-03": "Bungoma",
  "KE-04": "Busia",
  "KE-05": "Elgeyo/Marakwet",
  "KE-06": "Embu",
  "KE-07": "Garissa",
  "KE-08": "Homa Bay",
  "KE-09": "Isiolo",
  "KE-10": "Kajiado",
  "KE-11": "Kakamega",
  "KE-12": "Kericho",
  "KE-13": "Kiambu",
  "KE-14": "Kilifi",
  "KE-15": "Kirinyaga",
  "KE-16": "Kisii",
  "KE-17": "Kisumu",
  "KE-18": "Kitui",
  "KE-19": "Kwale",
  "KE-20": "Laikipia",
  "KE-21": "Lamu",
  "KE-22": "Machakos",
  "KE-23": "Makueni",
  "KE-24": "Mandera",
  "KE-25": "Marsabit",
  "KE-26": "Meru",
  "KE-27": "Migori",
  "KE-28": "Mombasa",
  "KE-29": "Murang'a",
  "KE-30": "Nairobi City",
  "KE-31": "Nakuru",
  "KE-32": "Nandi",
  "KE-33": "Narok",
  "KE-34": "Nyamira",
  "KE-35": "Nyandarua",
  "KE-36": "Nyeri",
  "KE-37": "Samburu",
  "KE-38": "Siaya",
  "KE-39": "Taita/Taveta",
  "KE-40": "Tana River",
  "KE-41": "Tharaka-Nithi",
  "KE-42": "Trans Nzoia",
  "KE-43": "Turkana",
  "KE-44": "Uasin Gishu",
  "KE-45": "Vihiga",
  "KE-46": "Wajir",
  "KE-47": "West Pokot",
  "LS-D": "Berea",
  "LS-B": "Botha-Bothe",
  "LS-C": "Leribe",
  "LS-E": "Mafeteng",
  "LS-A": "Maseru",
  "LS-F": "Mohale's Hoek",
  "LS-J": "Mokhotlong",
  "LS-H": "Qacha's Nek",
  "LS-G": "Quthing",
  "LS-K": "Thaba-Tseka",
  "LR-BM": "Bomi",
  "LR-BG": "Bong",
  "LR-GP": "Gbarpolu",
  "LR-GB": "Grand Bassa",
  "LR-CM": "Grand Cape Mount",
  "LR-GG": "Grand Gedeh",
  "LR-GK": "Grand Kru",
  "LR-LO": "Lofa",
  "LR-MG": "Margibi",
  "LR-MY": "Maryland",
  "LR-MO": "Montserrado",
  "LR-NI": "Nimba",
  "LR-RI": "River Cess",
  "LR-RG": "River Gee",
  "LR-SI": "Sinoe",
  "LY-BU": "Al Buţnān",
  "LY-JA": "Al Jabal al Akhḑar",
  "LY-JG": "Al Jabal al Gharbī",
  "LY-JI": "Al Jafārah",
  "LY-JU": "Al Jufrah",
  "LY-KF": "Al Kufrah",
  "LY-MJ": "Al Marj",
  "LY-MB": "Al Marqab",
  "LY-WA": "Al Wāḩāt",
  "LY-NQ": "An Nuqāţ al Khams",
  "LY-ZA": "Az Zāwiyah",
  "LY-BA": "Banghāzī",
  "LY-DR": "Darnah",
  "LY-GT": "Ghāt",
  "LY-MI": "Mişrātah",
  "LY-MQ": "Murzuq",
  "LY-NL": "Nālūt",
  "LY-SB": "Sabhā",
  "LY-SR": "Surt",
  "LY-TB": "Ţarābulus",
  "LY-WD": "Wādī al Ḩayāt",
  "LY-WS": "Wādī ash Shāţi’",
  "MG-T": "Antananarivo",
  "MG-D": "Antsiranana",
  "MG-F": "Fianarantsoa",
  "MG-M": "Mahajanga",
  "MG-A": "Toamasina",
  "MG-U": "Toliara",
  "MW-N": "Chakumpoto",
  "MW-S": "Chakumwera",
  "MW-C": "Chapakati",
  "ML-BKO": "Bamako",
  "ML-7": "Gao",
  "ML-1": "Kayes",
  "ML-8": "Kidal",
  "ML-2": "Koulikoro",
  "ML-9": "Ménaka",
  "ML-5": "Mopti",
  "ML-4": "Ségou",
  "ML-3": "Sikasso",
  "ML-10": "Taoudénit",
  "ML-6": "Tombouctou",
  "MR-07": "Adrar",
  "MR-03": "Assaba",
  "MR-05": "Brakna",
  "MR-08": "Dakhlet Nouâdhibou",
  "MR-04": "Gorgol",
  "MR-10": "Guidimaka",
  "MR-01": "Hodh ech Chargui",
  "MR-02": "Hodh el Gharbi",
  "MR-12": "Inchiri",
  "MR-09": "Tagant",
  "MR-11": "Tiris Zemmour",
  "MR-06": "Trarza",
  "MU-AG": "Agalega Islands",
  "MU-BL": "Black River",
  "MU-CC": "Cargados Carajos Shoals",
  "MU-FL": "Flacq",
  "MU-GP": "Grand Port",
  "MU-MO": "Moka",
  "MU-PA": "Pamplemousses",
  "MU-PW": "Plaines Wilhems",
  "MU-PL": "Port Louis",
  "MU-RR": "Rivière du Rempart",
  "MU-RO": "Rodrigues Island",
  "MU-SA": "Savanne",
  "MA-05": "Béni Mellal-Khénifra",
  "MA-06": "Casablanca-Settat",
  "MA-12": "Dakhla-Oued Ed-Dahab",
  "MA-08": "Drâa-Tafilalet",
  "MA-03": "Fès-Meknès",
  "MA-10": "Guelmim-Oued Noun",
  "MA-02": "L'Oriental",
  "MA-11": "Laâyoune-Sakia El Hamra",
  "MA-07": "Marrakech-Safi",
  "MA-04": "Rabat-Salé-Kénitra",
  "MA-09": "Souss-Massa",
  "MA-01": "Tanger-Tétouan-Al Hoceïma",
  "MZ-P": "Cabo Delgado",
  "MZ-G": "Gaza",
  "MZ-I": "Inhambane",
  "MZ-B": "Manica",
  "MZ-MPM": "Maputo",
  "MZ-L": "Maputo",
  "MZ-N": "Nampula",
  "MZ-A": "Niassa",
  "MZ-S": "Sofala",
  "MZ-T": "Tete",
  "MZ-Q": "Zambézia",
  "NA-ER": "Erongo",
  "NA-HA": "Hardap",
  "NA-KA": "//Karas",
  "NA-KE": "Kavango East",
  "NA-KW": "Kavango West",
  "NA-KH": "Khomas",
  "NA-KU": "Kunene",
  "NA-OW": "Ohangwena",
  "NA-OH": "Omaheke",
  "NA-OS": "Omusati",
  "NA-ON": "Oshana",
  "NA-OT": "Oshikoto",
  "NA-OD": "Otjozondjupa",
  "NA-CA": "Zambezi",
  "NE-1": "Agadez",
  "NE-2": "Diffa",
  "NE-3": "Dosso",
  "NE-4": "Maradi",
  "NE-8": "Niamey",
  "NE-5": "Tahoua",
  "NE-6": "Tillabéri",
  "NE-7": "Zinder",
  "NG-AB": "Abia",
  "NG-FC": "Abuja Federal Capital Territory",
  "NG-AD": "Adamawa",
  "NG-AK": "Akwa Ibom",
  "NG-AN": "Anambra",
  "NG-BA": "Bauchi",
  "NG-BY": "Bayelsa",
  "NG-BE": "Benue",
  "NG-BO": "Borno",
  "NG-CR": "Cross River",
  "NG-DE": "Delta",
  "NG-EB": "Ebonyi",
  "NG-ED": "Edo",
  "NG-EK": "Ekiti",
  "NG-EN": "Enugu",
  "NG-GO": "Gombe",
  "NG-IM": "Imo",
  "NG-JI": "Jigawa",
  "NG-KD": "Kaduna",
  "NG-KN": "Kano",
  "NG-KT": "Katsina",
  "NG-KE": "Kebbi",
  "NG-KO": "Kogi",
  "NG-KW": "Kwara",
  "NG-LA": "Lagos",
  "NG-NA": "Nasarawa",
  "NG-NI": "Niger",
  "NG-OG": "Ogun",
  "NG-ON": "Ondo",
  "NG-OS": "Osun",
  "NG-OY": "Oyo",
  "NG-PL": "Plateau",
  "NG-RI": "Rivers",
  "NG-SO": "Sokoto",
  "NG-TA": "Taraba",
  "NG-YO": "Yobe",
  "NG-ZA": "Zamfara",
  "RW-01": "City of Kigali",
  "RW-02": "Eastern",
  "RW-03": "Northern",
  "RW-05": "Southern",
  "RW-04": "Western",
  "SH-AC": "Ascension",
  "SH-HL": "Saint Helena",
  "SH-TA": "Tristan da Cunha",
  "ST-01": "Água Grande",
  "ST-02": "Cantagalo",
  "ST-03": "Caué",
  "ST-04": "Lembá",
  "ST-05": "Lobata",
  "ST-06": "Mé-Zóchi",
  "ST-P": "Príncipe",
  "SN-DK": "Dakar",
  "SN-DB": "Diourbel",
  "SN-FK": "Fatick",
  "SN-KA": "Kaffrine",
  "SN-KL": "Kaolack",
  "SN-KE": "Kédougou",
  "SN-KD": "Kolda",
  "SN-LG": "Louga",
  "SN-MT": "Matam",
  "SN-SL": "Saint-Louis",
  "SN-SE": "Sédhiou",
  "SN-TC": "Tambacounda",
  "SN-TH": "Thiès",
  "SN-ZG": "Ziguinchor",
  "SC-01": "Anse aux Pins",
  "SC-02": "Anse Boileau",
  "SC-03": "Anse Etoile",
  "SC-05": "Anse Royale",
  "SC-04": "Au Cap",
  "SC-06": "Baie Lazare",
  "SC-07": "Baie Sainte Anne",
  "SC-08": "Beau Vallon",
  "SC-09": "Bel Air",
  "SC-10": "Bel Ombre",
  "SC-11": "Cascade",
  "SC-16": "English River",
  "SC-12": "Glacis",
  "SC-13": "Grand Anse Mahe",
  "SC-14": "Grand Anse Praslin",
  "SC-26": "Ile Perseverance I",
  "SC-27": "Ile Perseverance II",
  "SC-15": "La Digue",
  "SC-24": "Les Mamelles",
  "SC-17": "Mont Buxton",
  "SC-18": "Mont Fleuri",
  "SC-19": "Plaisance",
  "SC-20": "Pointe Larue",
  "SC-21": "Port Glaud",
  "SC-25": "Roche Caiman",
  "SC-22": "Saint Louis",
  "SC-23": "Takamaka",
  "SL-E": "Eastern",
  "SL-NW": "North Western",
  "SL-N": "Northern",
  "SL-S": "Southern",
  "SL-W": "Western Area",
  "SO-AW": "Awdal",
  "SO-BK": "Bakool",
  "SO-BN": "Banaadir",
  "SO-BR": "Bari",
  "SO-BY": "Bay",
  "SO-GA": "Galguduud",
  "SO-GE": "Gedo",
  "SO-HI": "Hiiraan",
  "SO-JD": "Jubbada Dhexe",
  "SO-JH": "Jubbada Hoose",
  "SO-MU": "Mudug",
  "SO-NU": "Nugaal",
  "SO-SA": "Sanaag",
  "SO-SD": "Shabeellaha Dhexe",
  "SO-SH": "Shabeellaha Hoose",
  "SO-SO": "Sool",
  "SO-TO": "Togdheer",
  "SO-WO": "Woqooyi Galbeed",
  "ZA-EC": "Eastern Cape",
  "ZA-FS": "Free State",
  "ZA-GP": "Gauteng",
  "ZA-KZN": "Kwazulu-Natal",
  "ZA-LP": "Limpopo",
  "ZA-MP": "Mpumalanga",
  "ZA-NW": "North-West",
  "ZA-NC": "Northern Cape",
  "ZA-WC": "Western Cape",
  "SD-RS": "Al Baḩr al Aḩmar",
  "SD-GZ": "Al Jazīrah",
  "SD-KH": "Al Kharţūm",
  "SD-GD": "Al Qaḑārif",
  "SD-NW": "An Nīl al Abyaḑ",
  "SD-NB": "An Nīl al Azraq",
  "SD-NO": "Ash Shamālīyah",
  "SD-DW": "Gharb Dārfūr",
  "SD-GK": "Gharb Kurdufān",
  "SD-DS": "Janūb Dārfūr",
  "SD-KS": "Janūb Kurdufān",
  "SD-KA": "Kassalā",
  "SD-NR": "Nahr an Nīl",
  "SD-DN": "Shamāl Dārfūr",
  "SD-KN": "Shamāl Kurdufān",
  "SD-DE": "Sharq Dārfūr",
  "SD-SI": "Sinnār",
  "SD-DC": "Wasaţ Dārfūr",
  "SZ-HH": "Hhohho",
  "SZ-LU": "Lubombo",
  "SZ-MA": "Manzini",
  "SZ-SH": "Shiselweni",
  "TZ-01": "Arusha",
  "TZ-02": "Dar es Salaam",
  "TZ-03": "Dodoma",
  "TZ-27": "Geita",
  "TZ-04": "Iringa",
  "TZ-05": "Kagera",
  "TZ-06": "Kaskazini Pemba",
  "TZ-07": "Kaskazini Unguja",
  "TZ-28": "Katavi",
  "TZ-08": "Kigoma",
  "TZ-09": "Kilimanjaro",
  "TZ-10": "Kusini Pemba",
  "TZ-11": "Kusini Unguja",
  "TZ-12": "Lindi",
  "TZ-26": "Manyara",
  "TZ-13": "Mara",
  "TZ-14": "Mbeya",
  "TZ-15": "Mjini Magharibi",
  "TZ-16": "Morogoro",
  "TZ-17": "Mtwara",
  "TZ-18": "Mwanza",
  "TZ-29": "Njombe",
  "TZ-19": "Pwani",
  "TZ-20": "Rukwa",
  "TZ-21": "Ruvuma",
  "TZ-22": "Shinyanga",
  "TZ-30": "Simiyu",
  "TZ-23": "Singida",
  "TZ-31": "Songwe",
  "TZ-24": "Tabora",
  "TZ-25": "Tanga",
  "TG-C": "Centrale",
  "TG-K": "Kara",
  "TG-M": "Maritime",
  "TG-P": "Plateaux",
  "TG-S": "Savanes",
  "TN-31": "Béja",
  "TN-13": "Ben Arous",
  "TN-23": "Bizerte",
  "TN-81": "Gabès",
  "TN-71": "Gafsa",
  "TN-32": "Jendouba",
  "TN-41": "Kairouan",
  "TN-42": "Kasserine",
  "TN-73": "Kébili",
  "TN-12": "L'Ariana",
  "TN-14": "La Manouba",
  "TN-33": "Le Kef",
  "TN-53": "Mahdia",
  "TN-82": "Médenine",
  "TN-52": "Monastir",
  "TN-21": "Nabeul",
  "TN-61": "Sfax",
  "TN-43": "Sidi Bouzid",
  "TN-34": "Siliana",
  "TN-51": "Sousse",
  "TN-83": "Tataouine",
  "TN-72": "Tozeur",
  "TN-11": "Tunis",
  "TN-22": "Zaghouan",
  "UG-C": "Central",
  "UG-E": "Eastern",
  "UG-N": "Northern",
  "UG-W": "Western",
  "ZM-02": "Central",
  "ZM-08": "Copperbelt",
  "ZM-03": "Eastern",
  "ZM-04": "Luapula",
  "ZM-09": "Lusaka",
  "ZM-10": "Muchinga",
  "ZM-06": "North-Western",
  "ZM-05": "Northern",
  "ZM-07": "Southern",
  "ZM-01": "Western",
  "ZW-BU": "Bulawayo",
  "ZW-HA": "Harare",
  "ZW-MA": "Manicaland",
  "ZW-MC": "Mashonaland Central",
  "ZW-ME": "Mashonaland East",
  "ZW-MW": "Mashonaland West",
  "ZW-MV": "Masvingo",
  "ZW-MN": "Matabeleland North",
  "ZW-MS": "Matabeleland South",
  "ZW-MI": "Midlands",
  "SS-EC": "Central Equatoria",
  "SS-EE": "Eastern Equatoria",
  "SS-JG": "Jonglei",
  "SS-LK": "Lakes",
  "SS-BN": "Northern Bahr el Ghazal",
  "SS-UY": "Unity",
  "SS-NU": "Upper Nile",
  "SS-WR": "Warrap",
  "SS-BW": "Western Bahr el Ghazal",
  "SS-EW": "Western Equatoria",
};
