// ISO 3166-2 subdivisions for countries in Asia (continent code: AS)
export const ASIA_REGIONS: Record<string, string> = {
  "AF-BDS": "Badakhshān",
  "AF-BDG": "Bādghīs",
  "AF-BGL": "Baghlān",
  "AF-BAL": "Balkh",
  "AF-BAM": "Bāmyān",
  "AF-DAY": "Dāykundī",
  "AF-FRA": "Farāh",
  "AF-FYB": "Fāryāb",
  "AF-GHA": "Ghaznī",
  "AF-GHO": "Ghōr",
  "AF-HEL": "Helmand",
  "AF-HER": "Herāt",
  "AF-JOW": "Jowzjān",
  "AF-KAB": "Kābul",
  "AF-KAN": "Kandahār",
  "AF-KAP": "Kāpīsā",
  "AF-KHO": "Khōst",
  "AF-KNR": "Kunaṟ",
  "AF-KDZ": "Kunduz",
  "AF-LAG": "Laghmān",
  "AF-LOG": "Lōgar",
  "AF-NAN": "Nangarhār",
  "AF-NIM": "Nīmrōz",
  "AF-NUR": "Nūristān",
  "AF-PKA": "Paktīkā",
  "AF-PIA": "Paktiyā",
  "AF-PAN": "Panjshayr",
  "AF-PAR": "Parwān",
  "AF-SAM": "Samangān",
  "AF-SAR": "Sar-e Pul",
  "AF-TAK": "Takhār",
  "AF-URU": "Uruzgān",
  "AF-WAR": "Wardak",
  "AF-ZAB": "Zābul",
  "AM-AG": "Aragac̣otn",
  "AM-AR": "Ararat",
  "AM-AV": "Armavir",
  "AM-ER": "Erevan",
  "AM-GR": "Geġark'unik'",
  "AM-KT": "Kotayk'",
  "AM-LO": "Loṙi",
  "AM-SH": "Širak",
  "AM-SU": "Syunik'",
  "AM-TV": "Tavuš",
  "AM-VD": "Vayoć Jor",
  "AZ-NX": "Naxçıvan",
  "BH-13": "Al ‘Āşimah",
  "BH-14": "Al Janūbīyah",
  "BH-15": "Al Muḩarraq",
  "BH-17": "Ash Shamālīyah",
  "BD-A": "Barishal",
  "BD-B": "Chattogram",
  "BD-C": "Dhaka",
  "BD-D": "Khulna",
  "BD-H": "Mymensingh",
  "BD-E": "Rajshahi",
  "BD-F": "Rangpur",
  "BD-G": "Sylhet",
  "BT-33": "Bumthang",
  "BT-12": "Chhukha",
  "BT-22": "Dagana",
  "BT-GA": "Gasa",
  "BT-13": "Haa",
  "BT-44": "Lhuentse",
  "BT-42": "Monggar",
  "BT-11": "Paro",
  "BT-43": "Pema Gatshel",
  "BT-23": "Punakha",
  "BT-45": "Samdrup Jongkhar",
  "BT-14": "Samtse",
  "BT-31": "Sarpang",
  "BT-15": "Thimphu",
  "BT-41": "Trashigang",
  "BT-TY": "Trashi Yangtse",
  "BT-32": "Trongsa",
  "BT-21": "Tsirang",
  "BT-24": "Wangdue Phodrang",
  "BT-34": "Zhemgang",
  "BN-BE": "Belait",
  "BN-BM": "Brunei-Muara",
  "BN-TE": "Temburong",
  "BN-TU": "Tutong",
  "KH-2": "Baat Dambang",
  "KH-1": "Banteay Mean Choăy",
  "KH-23": "Kaeb",
  "KH-3": "Kampong Chaam",
  "KH-4": "Kampong Chhnang",
  "KH-5": "Kampong Spueu",
  "KH-6": "Kampong Thum",
  "KH-7": "Kampot",
  "KH-8": "Kandaal",
  "KH-9": "Kaoh Kong",
  "KH-10": "Kracheh",
  "KH-11": "Mondol Kiri",
  "KH-22": "Otdar Mean Chey",
  "KH-24": "Pailin",
  "KH-12": "Phnom Penh",
  "KH-15": "Pousaat",
  "KH-18": "Preah Sihanouk",
  "KH-13": "Preah Vihear",
  "KH-14": "Prey Veaeng",
  "KH-16": "Rotanak Kiri",
  "KH-17": "Siem Reab",
  "KH-19": "Stueng Traeng",
  "KH-20": "Svaay Rieng",
  "KH-21": "Taakaev",
  "KH-25": "Tbong Khmum",
  "CN-AH": "Anhui Sheng",
  "CN-BJ": "Beijing Shi",
  "CN-CQ": "Chongqing Shi",
  "CN-FJ": "Fujian Sheng",
  "CN-GS": "Gansu Sheng",
  "CN-GD": "Guangdong Sheng",
  "CN-GX": "Guangxi Zhuangzu Zizhiqu",
  "CN-GZ": "Guizhou Sheng",
  "CN-HI": "Hainan Sheng",
  "CN-HE": "Hebei Sheng",
  "CN-HL": "Heilongjiang Sheng",
  "CN-HA": "Henan Sheng",
  "CN-HK": "Hong Kong SARen",
  "CN-HB": "Hubei Sheng",
  "CN-HN": "Hunan Sheng",
  "CN-JS": "Jiangsu Sheng",
  "CN-JX": "Jiangxi Sheng",
  "CN-JL": "Jilin Sheng",
  "CN-LN": "Liaoning Sheng",
  "CN-MO": "Macao SARpt",
  "CN-NM": "Nei Mongol Zizhiqu",
  "CN-NX": "Ningxia Huizu Zizhiqu",
  "CN-QH": "Qinghai Sheng",
  "CN-SN": "Shaanxi Sheng",
  "CN-SD": "Shandong Sheng",
  "CN-SH": "Shanghai Shi",
  "CN-SX": "Shanxi Sheng",
  "CN-SC": "Sichuan Sheng",
  "CN-TW": "Taiwan Sheng",
  "CN-TJ": "Tianjin Shi",
  "CN-XJ": "Xinjiang Uygur Zizhiqu",
  "CN-XZ": "Xizang Zizhiqu",
  "CN-YN": "Yunnan Sheng",
  "CN-ZJ": "Zhejiang Sheng",
  "CY-04": "Ammochostos",
  "CY-06": "Keryneia",
  "CY-03": "Larnaka",
  "CY-01": "Lefkosia",
  "CY-02": "Lemesos",
  "CY-05": "Pafos",
  "GE-AB": "Abkhazia",
  "GE-AJ": "Ajaria",
  "GE-GU": "Guria",
  "GE-IM": "Imereti",
  "GE-KA": "K'akheti",
  "GE-KK": "Kvemo Kartli",
  "GE-MM": "Mtskheta-Mtianeti",
  "GE-RL": "Rach'a-Lechkhumi-Kvemo Svaneti",
  "GE-SZ": "Samegrelo-Zemo Svaneti",
  "GE-SJ": "Samtskhe-Javakheti",
  "GE-SK": "Shida Kartli",
  "GE-TB": "Tbilisi",
  "IN-AN": "Andaman and Nicobar Islands",
  "IN-AP": "Andhra Pradesh",
  "IN-AR": "Arunāchal Pradesh",
  "IN-AS": "Assam",
  "IN-BR": "Bihār",
  "IN-CH": "Chandīgarh",
  "IN-CG": "Chhattīsgarh",
  "IN-DH": "Dādra and Nagar Haveli and Damān and Diu[1]",
  "IN-DL": "Delhi",
  "IN-GA": "Goa",
  "IN-GJ": "Gujarāt",
  "IN-HR": "Haryāna",
  "IN-HP": "Himāchal Pradesh",
  "IN-JK": "Jammu and Kashmīr",
  "IN-JH": "Jhārkhand",
  "IN-KA": "Karnātaka",
  "IN-KL": "Kerala",
  "IN-LA": "Ladākh",
  "IN-LD": "Lakshadweep",
  "IN-MP": "Madhya Pradesh",
  "IN-MH": "Mahārāshtra",
  "IN-MN": "Manipur",
  "IN-ML": "Meghālaya",
  "IN-MZ": "Mizoram",
  "IN-NL": "Nāgāland",
  "IN-OD": "Odisha",
  "IN-PY": "Puducherry",
  "IN-PB": "Punjab",
  "IN-RJ": "Rājasthān",
  "IN-SK": "Sikkim",
  "IN-TN": "Tamil Nādu",
  "IN-TS": "Telangāna[2]",
  "IN-TR": "Tripura",
  "IN-UP": "Uttar Pradesh",
  "IN-UK": "Uttarākhand",
  "IN-WB": "West Bengal",
  "ID-JW": "Jawa",
  "ID-KA": "Kalimantan",
  "ID-ML": "Maluku",
  "ID-NU": "Nusa Tenggara",
  "ID-PP": "Papua",
  "ID-SL": "Sulawesi",
  "ID-SM": "Sumatera",
  "IR-30": "Alborz",
  "IR-24": "Ardabīl",
  "IR-04": "Āz̄ārbāyjān-e Ghārbī",
  "IR-03": "Āz̄ārbāyjān-e Shārqī",
  "IR-18": "Būshehr",
  "IR-14": "Chahār Maḩāl va Bakhtīārī",
  "IR-10": "Eşfahān",
  "IR-07": "Fārs",
  "IR-01": "Gīlān",
  "IR-27": "Golestān",
  "IR-13": "Hamadān",
  "IR-22": "Hormozgān",
  "IR-16": "Īlām",
  "IR-08": "Kermān",
  "IR-05": "Kermānshāh",
  "IR-29": "Khorāsān-e Jonūbī",
  "IR-09": "Khorāsān-e Raẕavī",
  "IR-28": "Khorāsān-e Shomālī",
  "IR-06": "Khūzestān",
  "IR-17": "Kohgīlūyeh va Bowyer Aḩmad",
  "IR-12": "Kordestān",
  "IR-15": "Lorestān",
  "IR-00": "Markazī",
  "IR-02": "Māzandarān",
  "IR-26": "Qazvīn",
  "IR-25": "Qom",
  "IR-20": "Semnān",
  "IR-11": "Sīstān va Balūchestān",
  "IR-23": "Tehrān",
  "IR-21": "Yazd",
  "IR-19": "Zanjān",
  "IQ-AN": "Al Anbār",
  "IQ-BA": "Al Başrah",
  "IQ-MU": "Al Muthanná",
  "IQ-QA": "Al Qādisīyah",
  "IQ-NA": "An Najaf",
  "IQ-AR": "Arbīl",
  "IQ-SU": "As Sulaymānīyah",
  "IQ-BB": "Bābil",
  "IQ-BG": "Baghdād",
  "IQ-DA": "Dahūk",
  "IQ-DQ": "Dhī Qār",
  "IQ-DI": "Diyālá",
  "IQ-KR": "Iqlīm Kūrdistān",
  "IQ-KA": "Karbalā’",
  "IQ-KI": "Kirkūk",
  "IQ-MA": "Maysān",
  "IQ-NI": "Nīnawá",
  "IQ-SD": "Şalāḩ ad Dīn",
  "IQ-WA": "Wāsiţ",
  "IL-D": "HaDarom",
  "IL-M": "HaMerkaz",
  "IL-Z": "HaTsafon",
  "IL-HA": "H̱efa",
  "IL-TA": "Tel Aviv",
  "IL-JM": "Yerushalayim",
  "JP-23": "Aiti",
  "JP-05": "Akita",
  "JP-02": "Aomori",
  "JP-38": "Ehime",
  "JP-21": "Gihu",
  "JP-10": "Gunma",
  "JP-34": "Hirosima",
  "JP-01": "Hokkaidô",
  "JP-18": "Hukui",
  "JP-40": "Hukuoka",
  "JP-07": "Hukusima",
  "JP-28": "Hyôgo",
  "JP-08": "Ibaraki",
  "JP-17": "Isikawa",
  "JP-03": "Iwate",
  "JP-37": "Kagawa",
  "JP-46": "Kagosima",
  "JP-14": "Kanagawa",
  "JP-39": "Kôti",
  "JP-43": "Kumamoto",
  "JP-26": "Kyôto",
  "JP-24": "Mie",
  "JP-04": "Miyagi",
  "JP-45": "Miyazaki",
  "JP-20": "Nagano",
  "JP-42": "Nagasaki",
  "JP-29": "Nara",
  "JP-15": "Niigata",
  "JP-44": "Ôita",
  "JP-33": "Okayama",
  "JP-47": "Okinawa",
  "JP-27": "Ôsaka",
  "JP-41": "Saga",
  "JP-11": "Saitama",
  "JP-25": "Siga",
  "JP-32": "Simane",
  "JP-22": "Sizuoka",
  "JP-12": "Tiba",
  "JP-36": "Tokusima",
  "JP-13": "Tôkyô",
  "JP-09": "Totigi",
  "JP-31": "Tottori",
  "JP-16": "Toyama",
  "JP-30": "Wakayama",
  "JP-06": "Yamagata",
  "JP-35": "Yamaguti",
  "JP-19": "Yamanasi",
  "JO-AJ": "‘Ajlūn",
  "JO-AQ": "Al ‘Aqabah",
  "JO-AM": "Al ‘A̅şimah",
  "JO-BA": "Al Balqā’",
  "JO-KA": "Al Karak",
  "JO-MA": "Al Mafraq",
  "JO-AT": "Aţ Ţafīlah",
  "JO-AZ": "Az Zarqā’",
  "JO-IR": "Irbid",
  "JO-JA": "Jarash",
  "JO-MN": "Ma‘ān",
  "JO-MD": "Mādabā",
  "KZ-10": "Abayoblysy",
  "KZ-75": "Almaty",
  "KZ-19": "Almatyoblysy",
  "KZ-11": "Aqmola oblysy",
  "KZ-15": "Aqtöbe oblysy",
  "KZ-71": "Astana",
  "KZ-23": "Atyraūoblysy",
  "KZ-27": "Batys Qazaqstan oblysy",
  "KZ-47": "Mangghystaū oblysy",
  "KZ-55": "Pavlodar oblysy",
  "KZ-35": "Qaraghandy oblysy",
  "KZ-39": "Qostanay oblysy",
  "KZ-43": "Qyzylorda oblysy",
  "KZ-63": "Shyghys Qazaqstan oblysy",
  "KZ-79": "Shymkent",
  "KZ-59": "Soltüstik Qazaqstan oblysy",
  "KZ-61": "Türkistan oblysy",
  "KZ-62": "Ulytaūoblysy",
  "KZ-31": "Zhambyl oblysy",
  "KZ-33": "Zhetisū oblysy",
  "KP-04": "Chagang-do",
  "KP-09": "Hamgyǒng-bukto",
  "KP-08": "Hamgyǒng-namdo",
  "KP-06": "Hwanghae-bukto",
  "KP-05": "Hwanghae-namdo",
  "KP-15": "Kaesŏng",
  "KP-07": "Kangwǒn-do",
  "KP-14": "Namp’o",
  "KP-03": "P'yǒngan-bukto",
  "KP-02": "P'yǒngan-namdo",
  "KP-01": "P'yǒngyang",
  "KP-13": "Rasǒn",
  "KP-10": "Ryanggang-do",
  "KR-26": "Busan-gwangyeoksi",
  "KR-43": "Chungcheongbuk-do",
  "KR-44": "Chungcheongnam-do",
  "KR-27": "Daegu-gwangyeoksi",
  "KR-30": "Daejeon-gwangyeoksi",
  "KR-42": "Gangwon-teukbyeoljachido",
  "KR-29": "Gwangju-gwangyeoksi",
  "KR-41": "Gyeonggi-do",
  "KR-47": "Gyeongsangbuk-do",
  "KR-48": "Gyeongsangnam-do",
  "KR-28": "Incheon-gwangyeoksi",
  "KR-49": "Jeju-teukbyeoljachido",
  "KR-45": "Jeollabuk-do",
  "KR-46": "Jeollanam-do",
  "KR-50": "Sejong",
  "KR-11": "Seoul-teukbyeolsi",
  "KR-31": "Ulsan-gwangyeoksi",
  "KW-AH": "Al Aḩmadī",
  "KW-FA": "Al Farwānīyah",
  "KW-JA": "Al Jahrā’",
  "KW-KU": "Al ‘Āşimah",
  "KW-HA": "Ḩawallī",
  "KW-MU": "Mubārak al Kabīr",
  "KG-B": "Batken",
  "KG-GB": "Bishkek Shaary",
  "KG-C": "Chüy",
  "KG-J": "Jalal-Abad",
  "KG-N": "Naryn",
  "KG-O": "Osh",
  "KG-GO": "Osh Shaary",
  "KG-T": "Talas",
  "KG-Y": "Ysyk-Köl",
  "LA-AT": "Attapu",
  "LA-BK": "Bokèo",
  "LA-BL": "Bolikhamxai",
  "LA-CH": "Champasak",
  "LA-HO": "Houaphan",
  "LA-KH": "Khammouan",
  "LA-LM": "Louang Namtha",
  "LA-LP": "Louangphabang",
  "LA-OU": "Oudômxai",
  "LA-PH": "Phôngsali",
  "LA-SL": "Salavan",
  "LA-SV": "Savannakhét",
  "LA-VI": "Viangchan",
  "LA-VT": "Viangchan",
  "LA-XA": "Xaignabouli",
  "LA-XS": "Xaisômboun",
  "LA-XE": "Xékong",
  "LA-XI": "Xiangkhouang",
  "LB-AK": "Aakkâr",
  "LB-BH": "Baalbek-Hermel",
  "LB-BI": "Béqaa",
  "LB-BA": "Beyrouth",
  "LB-AS": "Liban-Nord",
  "LB-JA": "Liban-Sud",
  "LB-JL": "Mont-Liban",
  "LB-NA": "Nabatîyé",
  "MY-01": "Johor",
  "MY-02": "Kedah",
  "MY-03": "Kelantan",
  "MY-04": "Melaka",
  "MY-05": "Negeri Sembilan",
  "MY-06": "Pahang",
  "MY-08": "Perak",
  "MY-09": "Perlis",
  "MY-07": "Pulau Pinang",
  "MY-12": "Sabah",
  "MY-13": "Sarawak",
  "MY-10": "Selangor",
  "MY-11": "Terengganu",
  "MY-14": "Wilayah Persekutuan Kuala Lumpur",
  "MY-15": "Wilayah Persekutuan Labuan",
  "MY-16": "Wilayah Persekutuan Putrajaya",
  "MV-01": "Addu",
  "MV-00": "Ariatholhu Dhekunuburi",
  "MV-02": "Ariatholhu Uthuruburi",
  "MV-03": "Faadhippolhu",
  "MV-04": "Felidheatholhu",
  "MV-29": "Fuvammulah",
  "MV-05": "Hahdhunmathi",
  "MV-28": "Huvadhuatholhu Dhekunuburi",
  "MV-27": "Huvadhuatholhu Uthuruburi",
  "MV-08": "Kolhumadulu",
  "MV-MLE": "Maale",
  "MV-26": "Maaleatholhu",
  "MV-20": "Maalhosmadulu Dhekunuburi",
  "MV-13": "Maalhosmadulu Uthuruburi",
  "MV-25": "Miladhunmadulu Dhekunuburi",
  "MV-24": "Miladhunmadulu Uthuruburi",
  "MV-12": "Mulakatholhu",
  "MV-17": "Nilandheatholhu Dhekunuburi",
  "MV-14": "Nilandheatholhu Uthuruburi",
  "MV-23": "Thiladhunmathee Dhekunuburi",
  "MV-07": "Thiladhunmathee Uthuruburi",
  "MN-073": "Arhangay",
  "MN-069": "Bayanhongor",
  "MN-071": "Bayan-Ölgiy",
  "MN-067": "Bulgan",
  "MN-037": "Darhan uul",
  "MN-061": "Dornod",
  "MN-063": "Dornogovĭ",
  "MN-059": "Dundgovĭ",
  "MN-057": "Dzavhan",
  "MN-065": "Govĭ-Altay",
  "MN-064": "Govĭ-Sümber",
  "MN-039": "Hentiy",
  "MN-043": "Hovd",
  "MN-041": "Hövsgöl",
  "MN-053": "Ömnögovĭ",
  "MN-035": "Orhon",
  "MN-055": "Övörhangay",
  "MN-049": "Selenge",
  "MN-051": "Sühbaatar",
  "MN-047": "Töv",
  "MN-1": "Ulaanbaatar",
  "MN-046": "Uvs",
  "MM-07": "Ayeyarwady",
  "MM-02": "Bago",
  "MM-14": "Chin",
  "MM-11": "Kachin",
  "MM-12": "Kayah",
  "MM-13": "Kayin",
  "MM-03": "Magway",
  "MM-04": "Mandalay",
  "MM-15": "Mon",
  "MM-18": "Nay Pyi Taw",
  "MM-16": "Rakhine",
  "MM-01": "Sagaing",
  "MM-17": "Shan",
  "MM-05": "Tanintharyi",
  "MM-06": "Yangon",
  "NP-P3": "Bāgmatī",
  "NP-P4": "Gaṇḍakī",
  "NP-P6": "Karṇālī",
  "NP-P1": "Koshī",
  "NP-P5": "Lumbinī",
  "NP-P2": "Madhesh",
  "NP-P7": "Sudūrpashchim",
  "OM-DA": "Ad Dākhilīyah",
  "OM-BU": "Al Buraymī",
  "OM-WU": "Al Wusţá",
  "OM-ZA": "Az̧ Z̧āhirah",
  "OM-BJ": "Janūb al Bāţinah",
  "OM-SJ": "Janūb ash Sharqīyah",
  "OM-MA": "Masqaţ",
  "OM-MU": "Musandam",
  "OM-BS": "Shamāl al Bāţinah",
  "OM-SS": "Shamāl ash Sharqīyah",
  "OM-ZU": "Z̧ufār",
  "PK-JK": "Āzād Jammūñ o Kashmīr",
  "PK-BA": "Balōchistān",
  "PK-GB": "Gilgit-Baltistān",
  "PK-IS": "Islāmābād",
  "PK-KP": "Khaībar Pakhtūnkhwā",
  "PK-PB": "Panjāb",
  "PK-SD": "Sindh",
  "PS-BTH": "Bayt Laḩm",
  "PS-DEB": "Dayr al Balaḩ",
  "PS-GZA": "Ghazzah",
  "PS-HBN": "Al Khalīl",
  "PS-JEN": "Janīn",
  "PS-JRH": "Arīḩā wal Aghwār",
  "PS-JEM": "Al Quds",
  "PS-KYS": "Khān Yūnis",
  "PS-NBS": "Nāblus",
  "PS-NGZ": "Shamāl Ghazzah",
  "PS-QQA": "Qalqīlyah",
  "PS-RFH": "Rafaḩ",
  "PS-RBH": "Rām Allāh wal Bīrah",
  "PS-SLT": "Salfīt",
  "PS-TBS": "Ţūbās",
  "PS-TKM": "Ţūlkarm",
  "PH-14": "Autonomous Region in Muslim Mindanao[b]",
  "PH-05": "Bicol",
  "PH-02": "Cagayan Valley",
  "PH-40": "Calabarzon",
  "PH-13": "Caraga",
  "PH-03": "Central Luzon",
  "PH-07": "Central Visayas",
  "PH-15": "Cordillera Administrative Region",
  "PH-11": "Davao",
  "PH-08": "Eastern Visayas",
  "PH-01": "Ilocos",
  "PH-41": "Mimaropa",
  "PH-00": "National Capital Region",
  "PH-10": "Northern Mindanao",
  "PH-12": "Soccsksargen",
  "PH-06": "Western Visayas",
  "PH-09": "Zamboanga Peninsula",
  "QA-DA": "Ad Dawḩah",
  "QA-KH": "Al Khawr wa adh Dhakhīrah",
  "QA-WA": "Al Wakrah",
  "QA-RA": "Ar Rayyān",
  "QA-MS": "Ash Shamāl",
  "QA-SH": "Ash Shīḩānīyah",
  "QA-ZA": "Az̧ Z̧a‘āyin",
  "QA-US": "Umm Şalāl",
  "SA-14": "'Asīr",
  "SA-11": "Al Bāḩah",
  "SA-08": "Al Ḩudūd ash Shamālīyah",
  "SA-12": "Al Jawf",
  "SA-03": "Al Madīnah al Munawwarah",
  "SA-05": "Al Qaşīm",
  "SA-01": "Ar Riyāḑ",
  "SA-04": "Ash Sharqīyah",
  "SA-06": "Ḩā'il",
  "SA-09": "Jāzān",
  "SA-02": "Makkah al Mukarramah",
  "SA-10": "Najrān",
  "SA-07": "Tabūk",
  "SG-01": "Central Singapore",
  "SG-02": "North East",
  "SG-03": "North West",
  "SG-04": "South East",
  "SG-05": "South West",
  "LK-1": "Basnāhira paḷāta",
  "LK-3": "Dakuṇu paḷāta",
  "LK-2": "Madhyama paḷāta",
  "LK-5": "Næ̆gĕnahira paḷāta",
  "LK-9": "Sabaragamuva paḷāta",
  "LK-4": "Uturu paḷāta",
  "LK-7": "Uturumæ̆da paḷāta",
  "LK-8": "Ūva paḷāta",
  "LK-6": "Vayamba paḷāta",
  "SY-HA": "Al Ḩasakah",
  "SY-LA": "Al Lādhiqīyah",
  "SY-QU": "Al Qunayţirah",
  "SY-RA": "Ar Raqqah",
  "SY-SU": "As Suwaydā'",
  "SY-DR": "Dar'ā",
  "SY-DY": "Dayr az Zawr",
  "SY-DI": "Dimashq",
  "SY-HL": "Ḩalab",
  "SY-HM": "Ḩamāh",
  "SY-HI": "Ḩimş",
  "SY-ID": "Idlib",
  "SY-RD": "Rīf Dimashq",
  "SY-TA": "Ţarţūs",
  "TW-CHA": "Changhua",
  "TW-CYI": "Chiayi",
  "TW-CYQ": "Chiayi",
  "TW-HSZ": "Hsinchu",
  "TW-HSQ": "Hsinchu",
  "TW-HUA": "Hualien",
  "TW-KHH": "Kaohsiung",
  "TW-KEE": "Keelung",
  "TW-KIN": "Kinmen",
  "TW-LIE": "Lienchiang",
  "TW-MIA": "Miaoli",
  "TW-NAN": "Nantou",
  "TW-NWT": "New Taipei",
  "TW-PEN": "Penghu",
  "TW-PIF": "Pingtung",
  "TW-TXG": "Taichung",
  "TW-TNN": "Tainan",
  "TW-TPE": "Taipei",
  "TW-TTT": "Taitung",
  "TW-TAO": "Taoyuan",
  "TW-ILA": "Yilan",
  "TW-YUN": "Yunlin",
  "TJ-DU": "Dushanbe",
  "TJ-KT": "Khatlon",
  "TJ-GB": "Kŭhistoni Badakhshon",
  "TJ-RA": "nohiyahoi tobei jumhurí",
  "TJ-SU": "Sughd",
  "TH-37": "Amnat Charoen",
  "TH-15": "Ang Thong",
  "TH-38": "Bueng Kan",
  "TH-31": "Buri Ram",
  "TH-24": "Chachoengsao",
  "TH-18": "Chai Nat",
  "TH-36": "Chaiyaphum",
  "TH-22": "Chanthaburi",
  "TH-50": "Chiang Mai",
  "TH-57": "Chiang Rai",
  "TH-20": "Chon Buri",
  "TH-86": "Chumphon",
  "TH-46": "Kalasin",
  "TH-62": "Kamphaeng Phet",
  "TH-71": "Kanchanaburi",
  "TH-40": "Khon Kaen",
  "TH-81": "Krabi",
  "TH-10": "Bangkok",
  "TH-52": "Lampang",
  "TH-51": "Lamphun",
  "TH-42": "Loei",
  "TH-16": "Lop Buri",
  "TH-58": "Mae Hong Son",
  "TH-44": "Maha Sarakham",
  "TH-49": "Mukdahan",
  "TH-26": "Nakhon Nayok",
  "TH-73": "Nakhon Pathom",
  "TH-48": "Nakhon Phanom",
  "TH-30": "Nakhon Ratchasima",
  "TH-60": "Nakhon Sawan",
  "TH-80": "Nakhon Si Thammarat",
  "TH-55": "Nan",
  "TH-96": "Narathiwat",
  "TH-39": "Nong Bua Lam Phu",
  "TH-43": "Nong Khai",
  "TH-12": "Nonthaburi",
  "TH-13": "Pathum Thani",
  "TH-94": "Pattani",
  "TH-82": "Phangnga",
  "TH-93": "Phatthalung",
  "TH-S": "Phatthaya",
  "TH-56": "Phayao",
  "TH-67": "Phetchabun",
  "TH-76": "Phetchaburi",
  "TH-66": "Phichit",
  "TH-65": "Phitsanulok",
  "TH-14": "Phra Nakhon Si Ayutthaya",
  "TH-54": "Phrae",
  "TH-83": "Phuket",
  "TH-25": "Prachin Buri",
  "TH-77": "Prachuap Khiri Khan",
  "TH-85": "Ranong",
  "TH-70": "Ratchaburi",
  "TH-21": "Rayong",
  "TH-45": "Roi Et",
  "TH-27": "Sa Kaeo",
  "TH-47": "Sakon Nakhon",
  "TH-11": "Samut Prakan",
  "TH-74": "Samut Sakhon",
  "TH-75": "Samut Songkhram",
  "TH-19": "Saraburi",
  "TH-91": "Satun",
  "TH-33": "Si Sa Ket",
  "TH-17": "Sing Buri",
  "TH-90": "Songkhla",
  "TH-64": "Sukhothai",
  "TH-72": "Suphan Buri",
  "TH-84": "Surat Thani",
  "TH-32": "Surin",
  "TH-63": "Tak",
  "TH-92": "Trang",
  "TH-23": "Trat",
  "TH-34": "Ubon Ratchathani",
  "TH-41": "Udon Thani",
  "TH-61": "Uthai Thani",
  "TH-53": "Uttaradit",
  "TH-95": "Yala",
  "TH-35": "Yasothon",
  "TL-AL": "Aileu",
  "TL-AN": "Ainaro",
  "TL-BA": "Baucau",
  "TL-BO": "Bobonaro",
  "TL-CO": "Cova Lima",
  "TL-DI": "Díli",
  "TL-ER": "Ermera",
  "TL-LA": "Lautém",
  "TL-LI": "Liquiça",
  "TL-MT": "Manatuto",
  "TL-MF": "Manufahi",
  "TL-OE": "Oé-Cusse Ambeno",
  "TL-VI": "Viqueque",
  "TR-01": "Adana",
  "TR-02": "Adıyaman",
  "TR-03": "Afyonkarahisar",
  "TR-04": "Ağrı",
  "TR-68": "Aksaray",
  "TR-05": "Amasya",
  "TR-06": "Ankara",
  "TR-07": "Antalya",
  "TR-75": "Ardahan",
  "TR-08": "Artvin",
  "TR-09": "Aydın",
  "TR-10": "Balıkesir",
  "TR-74": "Bartın",
  "TR-72": "Batman",
  "TR-69": "Bayburt",
  "TR-11": "Bilecik",
  "TR-12": "Bingöl",
  "TR-13": "Bitlis",
  "TR-14": "Bolu",
  "TR-15": "Burdur",
  "TR-16": "Bursa",
  "TR-17": "Çanakkale",
  "TR-18": "Çankırı",
  "TR-19": "Çorum",
  "TR-20": "Denizli",
  "TR-21": "Diyarbakır",
  "TR-81": "Düzce",
  "TR-22": "Edirne",
  "TR-23": "Elazığ",
  "TR-24": "Erzincan",
  "TR-25": "Erzurum",
  "TR-26": "Eskişehir",
  "TR-27": "Gaziantep",
  "TR-28": "Giresun",
  "TR-29": "Gümüşhane",
  "TR-30": "Hakkâri",
  "TR-31": "Hatay",
  "TR-76": "Iğdır",
  "TR-32": "Isparta",
  "TR-34": "İstanbul",
  "TR-35": "İzmir",
  "TR-46": "Kahramanmaraş",
  "TR-78": "Karabük",
  "TR-70": "Karaman",
  "TR-36": "Kars",
  "TR-37": "Kastamonu",
  "TR-38": "Kayseri",
  "TR-71": "Kırıkkale",
  "TR-39": "Kırklareli",
  "TR-40": "Kırşehir",
  "TR-79": "Kilis",
  "TR-41": "Kocaeli",
  "TR-42": "Konya",
  "TR-43": "Kütahya",
  "TR-44": "Malatya",
  "TR-45": "Manisa",
  "TR-47": "Mardin",
  "TR-33": "Mersin",
  "TR-48": "Muğla",
  "TR-49": "Muş",
  "TR-50": "Nevşehir",
  "TR-51": "Niğde",
  "TR-52": "Ordu",
  "TR-80": "Osmaniye",
  "TR-53": "Rize",
  "TR-54": "Sakarya",
  "TR-55": "Samsun",
  "TR-56": "Siirt",
  "TR-57": "Sinop",
  "TR-58": "Sivas",
  "TR-63": "Şanlıurfa",
  "TR-73": "Şırnak",
  "TR-59": "Tekirdağ",
  "TR-60": "Tokat",
  "TR-61": "Trabzon",
  "TR-62": "Tunceli",
  "TR-64": "Uşak",
  "TR-65": "Van",
  "TR-77": "Yalova",
  "TR-66": "Yozgat",
  "TR-67": "Zonguldak",
  "TM-A": "Ahal",
  "TM-S": "Aşgabat",
  "TM-B": "Balkan",
  "TM-D": "Daşoguz",
  "TM-L": "Lebap",
  "TM-M": "Mary",
  "AE-AJ": "‘Ajmān",
  "AE-AZ": "Abū Z̧aby",
  "AE-FU": "Al Fujayrah",
  "AE-SH": "Ash Shāriqah",
  "AE-DU": "Dubayy",
  "AE-RK": "Ra’s al Khaymah",
  "AE-UQ": "Umm al Qaywayn",
  "UZ-AN": "Andijon",
  "UZ-BU": "Buxoro",
  "UZ-FA": "Farg‘ona",
  "UZ-JI": "Jizzax",
  "UZ-NG": "Namangan",
  "UZ-NW": "Navoiy",
  "UZ-QA": "Qashqadaryo",
  "UZ-QR": "Qoraqalpog‘iston Respublikasi",
  "UZ-SA": "Samarqand",
  "UZ-SI": "Sirdaryo",
  "UZ-SU": "Surxondaryo",
  "UZ-TK": "Toshkent",
  "UZ-TO": "Toshkent",
  "UZ-XO": "Xorazm",
  "VN-44": "An Giang",
  "VN-43": "Bà Rịa - Vũng Tàu",
  "VN-54": "Bắc Giang",
  "VN-53": "Bắc Kạn",
  "VN-55": "Bạc Liêu",
  "VN-56": "Bắc Ninh",
  "VN-50": "Bến Tre",
  "VN-31": "Bình Định",
  "VN-57": "Bình Dương",
  "VN-58": "Bình Phước",
  "VN-40": "Bình Thuận",
  "VN-59": "Cà Mau",
  "VN-CT": "Cần Thơ",
  "VN-04": "Cao Bằng",
  "VN-DN": "Đà Nẵng",
  "VN-33": "Đắk Lắk",
  "VN-72": "Đắk Nông",
  "VN-71": "Điện Biên",
  "VN-39": "Đồng Nai",
  "VN-45": "Đồng Tháp",
  "VN-30": "Gia Lai",
  "VN-03": "Hà Giang",
  "VN-63": "Hà Nam",
  "VN-HN": "Hà Nội",
  "VN-23": "Hà Tĩnh",
  "VN-61": "Hải Dương",
  "VN-HP": "Hải Phòng",
  "VN-73": "Hậu Giang",
  "VN-SG": "Hồ Chí Minh",
  "VN-14": "Hòa Bình",
  "VN-66": "Hưng Yên",
  "VN-34": "Khánh Hòa",
  "VN-47": "Kiến Giang",
  "VN-28": "Kon Tum",
  "VN-01": "Lai Châu",
  "VN-35": "Lâm Đồng",
  "VN-09": "Lạng Sơn",
  "VN-02": "Lào Cai",
  "VN-41": "Long An",
  "VN-67": "Nam Định",
  "VN-22": "Nghệ An",
  "VN-18": "Ninh Bình",
  "VN-36": "Ninh Thuận",
  "VN-68": "Phú Thọ",
  "VN-32": "Phú Yên",
  "VN-24": "Quảng Bình",
  "VN-27": "Quảng Nam",
  "VN-29": "Quảng Ngãi",
  "VN-13": "Quảng Ninh",
  "VN-25": "Quảng Trị",
  "VN-52": "Sóc Trăng",
  "VN-05": "Sơn La",
  "VN-37": "Tây Ninh",
  "VN-20": "Thái Bình",
  "VN-69": "Thái Nguyên",
  "VN-21": "Thanh Hóa",
  "VN-26": "Thừa Thiên-Huế",
  "VN-46": "Tiền Giang",
  "VN-51": "Trà Vinh",
  "VN-07": "Tuyên Quang",
  "VN-49": "Vĩnh Long",
  "VN-70": "Vĩnh Phúc",
  "VN-06": "Yên Bái",
  "YE-AD": "‘Adan",
  "YE-AM": "‘Amrān",
  "YE-AB": "Abyan",
  "YE-DA": "Aḑ Ḑāli‘",
  "YE-BA": "Al Bayḑā’",
  "YE-HU": "Al Ḩudaydah",
  "YE-JA": "Al Jawf",
  "YE-MR": "Al Mahrah",
  "YE-MW": "Al Maḩwīt",
  "YE-SA": "Amānat al ‘Āşimah",
  "YE-SU": "Arkhabīl Suquţrá",
  "YE-DH": "Dhamār",
  "YE-HD": "Ḩaḑramawt",
  "YE-HJ": "Ḩajjah",
  "YE-IB": "Ibb",
  "YE-LA": "Laḩij",
  "YE-MA": "Ma’rib",
  "YE-RA": "Raymah",
  "YE-SD": "Şāʻdah",
  "YE-SN": "Şanʻā’",
  "YE-SH": "Shabwah",
  "YE-TA": "Tāʻizz",
};
