// ISO 3166-2 subdivisions for countries in Europe (continent code: EU)
export const EUROPE_REGIONS: Record<string, string> = {
  "AL-01": "Berat",
  "AL-09": "Dibër",
  "AL-02": "Durrës",
  "AL-03": "Elbasan",
  "AL-04": "Fier",
  "AL-05": "Gjirokastër",
  "AL-06": "Korçë",
  "AL-07": "Kukës",
  "AL-08": "Lezhë",
  "AL-10": "Shkodër",
  "AL-11": "Tiranë",
  "AL-12": "Vlorë",
  "AD-07": "Andorra la Vella",
  "AD-02": "Canillo",
  "AD-03": "Encamp",
  "AD-08": "Escaldes-Engordany",
  "AD-04": "La Massana",
  "AD-05": "Ordino",
  "AD-06": "Sant Julià de Lòria",
  "AT-1": "Burgenland",
  "AT-2": "Kärnten",
  "AT-3": "Niederösterreich",
  "AT-4": "Oberösterreich",
  "AT-5": "Salzburg",
  "AT-6": "Steiermark",
  "AT-7": "Tirol",
  "AT-8": "Vorarlberg",
  "AT-9": "Wien",
  "BY-BR": "Brestskaya voblasts'",
  "BY-HO": "Homyel'skaya voblasts'",
  "BY-HM": "Horad Minsk",
  "BY-HR": "Hrodzyenskaya voblasts'",
  "BY-MA": "Mahilyowskaya voblasts'",
  "BY-MI": "Minskaya voblasts'",
  "BY-VI": "Vitsyebskaya voblasts'",
  "BE-BRU": "Brussels Hoofdstedelijk Gewest",
  "BE-VLG": "Vlaams Gewest",
  "BE-WAL": "Waals Gewest[note 2]",
  "BA-BIH": "Federacija Bosne i Hercegovine",
  "BA-SRP": "Republika Srpska",
  "BA-BRC": "Brčko distrikt",
  "BG-01": "Blagoevgrad",
  "BG-02": "Burgas",
  "BG-08": "Dobrich",
  "BG-07": "Gabrovo",
  "BG-26": "Haskovo",
  "BG-09": "Kardzhali",
  "BG-10": "Kyustendil",
  "BG-11": "Lovech",
  "BG-12": "Montana",
  "BG-13": "Pazardzhik",
  "BG-14": "Pernik",
  "BG-15": "Pleven",
  "BG-16": "Plovdiv",
  "BG-17": "Razgrad",
  "BG-18": "Ruse",
  "BG-27": "Shumen",
  "BG-19": "Silistra",
  "BG-20": "Sliven",
  "BG-21": "Smolyan",
  "BG-23": "Sofia",
  "BG-22": "Sofia (stolitsa)",
  "BG-24": "Stara Zagora",
  "BG-25": "Targovishte",
  "BG-03": "Varna",
  "BG-04": "Veliko Tarnovo",
  "BG-05": "Vidin",
  "BG-06": "Vratsa",
  "BG-28": "Yambol",
  "HR-07": "Bjelovarsko-bilogorska županija",
  "HR-12": "Brodsko-posavska županija",
  "HR-19": "Dubrovačko-neretvanska županija",
  "HR-21": "Grad Zagreb",
  "HR-18": "Istarska županija",
  "HR-04": "Karlovačka županija",
  "HR-06": "Koprivničko-križevačka županija",
  "HR-02": "Krapinsko-zagorska županija",
  "HR-09": "Ličko-senjska županija",
  "HR-20": "Međimurska županija",
  "HR-14": "Osječko-baranjska županija",
  "HR-11": "Požeško-slavonska županija",
  "HR-08": "Primorsko-goranska županija",
  "HR-03": "Sisačko-moslavačka županija",
  "HR-17": "Splitsko-dalmatinska županija",
  "HR-15": "Šibensko-kninska županija",
  "HR-05": "Varaždinska županija",
  "HR-10": "Virovitičko-podravska županija",
  "HR-16": "Vukovarsko-srijemska županija",
  "HR-13": "Zadarska županija",
  "HR-01": "Zagrebačka županija",
  "CZ-31": "Jihočeský kraj",
  "CZ-64": "Jihomoravský kraj",
  "CZ-41": "Karlovarský kraj",
  "CZ-52": "Královéhradecký kraj",
  "CZ-51": "Liberecký kraj",
  "CZ-80": "Moravskoslezský kraj",
  "CZ-71": "Olomoucký kraj",
  "CZ-53": "Pardubický kraj",
  "CZ-32": "Plzeňský kraj",
  "CZ-10": "Praha",
  "CZ-20": "Středočeský kraj",
  "CZ-42": "Ústecký kraj",
  "CZ-63": "Kraj Vysočina",
  "CZ-72": "Zlínský kraj",
  "DK-84": "Region Hovedstaden",
  "DK-82": "Region Midjylland",
  "DK-81": "Region Nordjylland",
  "DK-85": "Region Sjælland",
  "DK-83": "Region Syddanmark",
  "EE-37": "Harjumaa",
  "EE-39": "Hiiumaa",
  "EE-45": "Ida-Virumaa",
  "EE-50": "Jõgevamaa",
  "EE-52": "Järvamaa",
  "EE-60": "Lääne-Virumaa",
  "EE-56": "Läänemaa",
  "EE-64": "Põlvamaa",
  "EE-68": "Pärnumaa",
  "EE-71": "Raplamaa",
  "EE-74": "Saaremaa",
  "EE-79": "Tartumaa",
  "EE-81": "Valgamaa",
  "EE-84": "Viljandimaa",
  "EE-87": "Võrumaa",
  "FI-01": "Ahvenanmaan maakunta",
  "FI-02": "Etelä-Karjala",
  "FI-03": "Etelä-Pohjanmaa",
  "FI-04": "Etelä-Savo",
  "FI-05": "Kainuu",
  "FI-06": "Kanta-Häme",
  "FI-07": "Keski-Pohjanmaa",
  "FI-08": "Keski-Suomi",
  "FI-09": "Kymenlaakso",
  "FI-10": "Lappi",
  "FI-11": "Pirkanmaa",
  "FI-12": "Pohjanmaa",
  "FI-13": "Pohjois-Karjala",
  "FI-14": "Pohjois-Pohjanmaa",
  "FI-15": "Pohjois-Savo",
  "FI-16": "Päijät-Häme",
  "FI-17": "Satakunta",
  "FI-18": "Uusimaa",
  "FI-19": "Varsinais-Suomi",
  "FR-ARA": "Auvergne-Rhône-Alpes",
  "FR-BFC": "Bourgogne-Franche-Comté",
  "FR-BRE": "Bretagne",
  "FR-CVL": "Centre-Val de Loire",
  "FR-20R": "Corse",
  "FR-GES": "Grand Est",
  "FR-HDF": "Hauts-de-France",
  "FR-IDF": "Île-de-France",
  "FR-NOR": "Normandie",
  "FR-NAQ": "Nouvelle-Aquitaine",
  "FR-OCC": "Occitanie",
  "FR-PDL": "Pays-de-la-Loire",
  "FR-PAC": "Provence-Alpes-Côte-d’Azur",
  "DE-BW": "Baden-Württemberg",
  "DE-BY": "Bayern",
  "DE-BE": "Berlin",
  "DE-BB": "Brandenburg",
  "DE-HB": "Bremen",
  "DE-HH": "Hamburg",
  "DE-HE": "Hessen",
  "DE-MV": "Mecklenburg-Vorpommern",
  "DE-NI": "Niedersachsen",
  "DE-NW": "Nordrhein-Westfalen",
  "DE-RP": "Rheinland-Pfalz",
  "DE-SL": "Saarland",
  "DE-SN": "Sachsen",
  "DE-ST": "Sachsen-Anhalt",
  "DE-SH": "Schleswig-Holstein",
  "DE-TH": "Thüringen",
  "GR-69": "Ágion Óros",
  "GR-A": "Anatolikí Makedonía kaiThráki",
  "GR-I": "Attikí",
  "GR-G": "Dytikí Elláda",
  "GR-C": "Dytikí Makedonía",
  "GR-F": "Ionía Nísia",
  "GR-D": "Ípeiros",
  "GR-B": "Kentrikí Makedonía",
  "GR-M": "Kríti",
  "GR-L": "Nótio Aigaío",
  "GR-J": "Pelopónnisos",
  "GR-H": "Stereá Elláda",
  "GR-E": "Thessalía",
  "GR-K": "Vóreio Aigaío",
  "HU-BK": "Bács-Kiskun",
  "HU-BA": "Baranya",
  "HU-BE": "Békés",
  "HU-BC": "Békéscsaba",
  "HU-BZ": "Borsod-Abaúj-Zemplén",
  "HU-BU": "Budapest",
  "HU-CS": "Csongrád-Csanád",
  "HU-DE": "Debrecen",
  "HU-DU": "Dunaújváros",
  "HU-EG": "Eger",
  "HU-ER": "Érd",
  "HU-FE": "Fejér",
  "HU-GY": "Győr",
  "HU-GS": "Győr-Moson-Sopron",
  "HU-HB": "Hajdú-Bihar",
  "HU-HE": "Heves",
  "HU-HV": "Hódmezővásárhely",
  "HU-JN": "Jász-Nagykun-Szolnok",
  "HU-KV": "Kaposvár",
  "HU-KM": "Kecskemét",
  "HU-KE": "Komárom-Esztergom",
  "HU-MI": "Miskolc",
  "HU-NK": "Nagykanizsa",
  "HU-NO": "Nógrád",
  "HU-NY": "Nyíregyháza",
  "HU-PS": "Pécs",
  "HU-PE": "Pest",
  "HU-ST": "Salgótarján",
  "HU-SO": "Somogy",
  "HU-SN": "Sopron",
  "HU-SZ": "Szabolcs-Szatmár-Bereg",
  "HU-SD": "Szeged",
  "HU-SF": "Székesfehérvár",
  "HU-SS": "Szekszárd",
  "HU-SK": "Szolnok",
  "HU-SH": "Szombathely",
  "HU-TB": "Tatabánya",
  "HU-TO": "Tolna",
  "HU-VA": "Vas",
  "HU-VM": "Veszprém",
  "HU-VE": "Veszprém",
  "HU-ZA": "Zala",
  "HU-ZE": "Zalaegerszeg",
  "IS-7": "Austurland",
  "IS-1": "Höfuðborgarsvæði",
  "IS-6": "Norðurland eystra",
  "IS-5": "Norðurland vestra",
  "IS-8": "Suðurland",
  "IS-2": "Suðurnes",
  "IS-4": "Vestfirðir",
  "IS-3": "Vesturland",
  "IE-C": "Connaught",
  "IE-L": "Leinster",
  "IE-M": "Munster",
  "IE-U": "Ulster[a]",
  "IT-65": "Abruzzo",
  "IT-77": "Basilicata",
  "IT-78": "Calabria",
  "IT-72": "Campania",
  "IT-45": "Emilia-Romagna",
  "IT-36": "Friuli Venezia Giulia",
  "IT-62": "Lazio",
  "IT-42": "Liguria",
  "IT-25": "Lombardia",
  "IT-57": "Marche",
  "IT-67": "Molise",
  "IT-21": "Piemonte",
  "IT-75": "Puglia",
  "IT-88": "Sardegna",
  "IT-82": "Sicilia",
  "IT-52": "Toscana",
  "IT-32": "Trentino-Alto Adigede",
  "IT-55": "Umbria",
  "IT-23": "Valle d'Aostafr",
  "IT-34": "Veneto",
  "LV-002": "Aizkraukles novads",
  "LV-007": "Alūksnes novads",
  "LV-111": "Augšdaugavas novads",
  "LV-011": "Ādažu novads",
  "LV-015": "Balvu novads",
  "LV-016": "Bauskas novads",
  "LV-022": "Cēsu novads",
  "LV-DGV": "Daugavpils",
  "LV-112": "Dienvidkurzemes Novads",
  "LV-026": "Dobeles novads",
  "LV-033": "Gulbenes novads",
  "LV-JEL": "Jelgava",
  "LV-041": "Jelgavas novads",
  "LV-042": "Jēkabpils novads",
  "LV-JUR": "Jūrmala",
  "LV-047": "Krāslavas novads",
  "LV-050": "Kuldīgas novads",
  "LV-052": "Ķekavas novads",
  "LV-LPX": "Liepāja",
  "LV-054": "Limbažu novads",
  "LV-056": "Līvānu novads",
  "LV-058": "Ludzas novads",
  "LV-059": "Madonas novads",
  "LV-062": "Mārupes novads",
  "LV-067": "Ogres novads",
  "LV-068": "Olaines novads",
  "LV-073": "Preiļu novads",
  "LV-REZ": "Rēzekne",
  "LV-077": "Rēzeknes novads",
  "LV-RIX": "Rīga",
  "LV-080": "Ropažu novads",
  "LV-087": "Salaspils novads",
  "LV-088": "Saldus novads",
  "LV-089": "Saulkrastu novads",
  "LV-091": "Siguldas novads",
  "LV-094": "Smiltenes novads",
  "LV-097": "Talsu novads",
  "LV-099": "Tukuma novads",
  "LV-101": "Valkas novads",
  "LV-113": "Valmieras Novads",
  "LV-102": "Varakļānu novads",
  "LV-VEN": "Ventspils",
  "LV-106": "Ventspils novads",
  "LI-01": "Balzers",
  "LI-02": "Eschen",
  "LI-03": "Gamprin",
  "LI-04": "Mauren",
  "LI-05": "Planken",
  "LI-06": "Ruggell",
  "LI-07": "Schaan",
  "LI-08": "Schellenberg",
  "LI-09": "Triesen",
  "LI-10": "Triesenberg",
  "LI-11": "Vaduz",
  "LT-AL": "Alytaus apskritis",
  "LT-KU": "Kauno apskritis",
  "LT-KL": "Klaipėdos apskritis",
  "LT-MR": "Marijampolės apskritis",
  "LT-PN": "Panevėžio apskritis",
  "LT-SA": "Šiaulių apskritis",
  "LT-TA": "Tauragės apskritis",
  "LT-TE": "Telšių apskritis",
  "LT-UT": "Utenos apskritis",
  "LT-VL": "Vilniaus apskritis",
  "LU-CA": "Capellen",
  "LU-CL": "Clervaux",
  "LU-DI": "Diekirch",
  "LU-EC": "Echternach",
  "LU-ES": "Esch-sur-Alzette",
  "LU-GR": "Grevenmacher",
  "LU-LU": "Luxembourg",
  "LU-ME": "Mersch",
  "LU-RD": "Redange",
  "LU-RM": "Remich",
  "LU-VD": "Vianden",
  "LU-WI": "Wiltz",
  "MT-01": "Attard",
  "MT-02": "Balzan",
  "MT-03": "Birgu",
  "MT-04": "Birkirkara",
  "MT-05": "Birżebbuġa",
  "MT-06": "Bormla",
  "MT-07": "Dingli",
  "MT-08": "Fgura",
  "MT-09": "Floriana",
  "MT-10": "Fontana",
  "MT-11": "Gudja",
  "MT-12": "Gżira",
  "MT-13": "Għajnsielem",
  "MT-14": "Għarb",
  "MT-15": "Għargħur",
  "MT-16": "Għasri",
  "MT-17": "Għaxaq",
  "MT-18": "Ħamrun",
  "MT-19": "Iklin",
  "MT-20": "Isla",
  "MT-21": "Kalkara",
  "MT-22": "Kerċem",
  "MT-23": "Kirkop",
  "MT-24": "Lija",
  "MT-25": "Luqa",
  "MT-26": "Marsa",
  "MT-27": "Marsaskala",
  "MT-28": "Marsaxlokk",
  "MT-29": "Mdina",
  "MT-30": "Mellieħa",
  "MT-31": "Mġarr",
  "MT-32": "Mosta",
  "MT-33": "Mqabba",
  "MT-34": "Msida",
  "MT-35": "Mtarfa",
  "MT-36": "Munxar",
  "MT-37": "Nadur",
  "MT-38": "Naxxar",
  "MT-39": "Paola",
  "MT-40": "Pembroke",
  "MT-41": "Pietà",
  "MT-42": "Qala",
  "MT-43": "Qormi",
  "MT-44": "Qrendi",
  "MT-45": "Rabat Għawdex",
  "MT-46": "Rabat Malta",
  "MT-47": "Safi",
  "MT-48": "San Ġiljan",
  "MT-49": "San Ġwann",
  "MT-50": "San Lawrenz",
  "MT-51": "San Pawl il-Baħar",
  "MT-52": "Sannat",
  "MT-53": "Santa Luċija",
  "MT-54": "Santa Venera",
  "MT-55": "Siġġiewi",
  "MT-56": "Sliema",
  "MT-57": "Swieqi",
  "MT-58": "Ta' Xbiex",
  "MT-59": "Tarxien",
  "MT-60": "Valletta",
  "MT-61": "Xagħra",
  "MT-62": "Xewkija",
  "MT-63": "Xgħajra",
  "MT-64": "Żabbar",
  "MT-65": "Żebbuġ Għawdex",
  "MT-66": "Żebbuġ Malta",
  "MT-67": "Żejtun",
  "MT-68": "Żurrieq",
  "MD-AN": "Anenii Noi",
  "MD-BS": "Basarabeasca",
  "MD-BA": "Bălți",
  "MD-BD": "Bender",
  "MD-BR": "Briceni",
  "MD-CA": "Cahul",
  "MD-CT": "Cantemir",
  "MD-CL": "Călărași",
  "MD-CS": "Căușeni",
  "MD-CU": "Chișinău",
  "MD-CM": "Cimișlia",
  "MD-CR": "Criuleni",
  "MD-DO": "Dondușeni",
  "MD-DR": "Drochia",
  "MD-DU": "Dubăsari",
  "MD-ED": "Edineț",
  "MD-FA": "Fălești",
  "MD-FL": "Florești",
  "MD-GA": "Găgăuzia",
  "MD-GL": "Glodeni",
  "MD-HI": "Hîncești",
  "MD-IA": "Ialoveni",
  "MD-LE": "Leova",
  "MD-NI": "Nisporeni",
  "MD-OC": "Ocnița",
  "MD-OR": "Orhei",
  "MD-RE": "Rezina",
  "MD-RI": "Rîșcani",
  "MD-SI": "Sîngerei",
  "MD-SO": "Soroca",
  "MD-SN": "Stînga Nistrului",
  "MD-ST": "Strășeni",
  "MD-SD": "Șoldănești",
  "MD-SV": "Ștefan Vodă",
  "MD-TA": "Taraclia",
  "MD-TE": "Telenești",
  "MD-UN": "Ungheni",
  "MC-FO": "Fontvieille",
  "MC-JE": "Jardin Exotique",
  "MC-CL": "La Colle",
  "MC-CO": "La Condamine",
  "MC-GA": "La Gare",
  "MC-SO": "La Source",
  "MC-LA": "Larvotto",
  "MC-MA": "Malbousquet",
  "MC-MO": "Monaco-Ville",
  "MC-MG": "Moneghetti",
  "MC-MC": "Monte-Carlo",
  "MC-MU": "Moulins",
  "MC-PH": "Port-Hercule",
  "MC-SR": "Saint-Roman",
  "MC-SD": "Sainte-Dévote",
  "MC-SP": "Spélugues",
  "MC-VR": "Vallon de la Rousse",
  "NL-DR": "Drenthe",
  "NL-FL": "Flevoland",
  "NL-FR": "Fryslânfy",
  "NL-GE": "Gelderland",
  "NL-GR": "Groningen",
  "NL-LI": "Limburg",
  "NL-NB": "Noord-Brabant",
  "NL-NH": "Noord-Holland",
  "NL-OV": "Overijssel",
  "NL-UT": "Utrecht",
  "NL-ZE": "Zeeland",
  "NL-ZH": "Zuid-Holland",
  "MK-801": "Aerodrom",
  "MK-802": "Aračinovo",
  "MK-201": "Berovo",
  "MK-501": "Bitola",
  "MK-401": "Bogdanci",
  "MK-601": "Bogovinje",
  "MK-402": "Bosilovo",
  "MK-602": "Brvenica",
  "MK-803": "Butel",
  "MK-814": "Centar",
  "MK-313": "Centar Župa",
  "MK-815": "Čair",
  "MK-109": "Čaška",
  "MK-210": "Češinovo-Obleševo",
  "MK-816": "Čučer-Sandevo",
  "MK-303": "Debar",
  "MK-304": "Debrca",
  "MK-203": "Delčevo",
  "MK-502": "Demir Hisar",
  "MK-103": "Demir Kapija",
  "MK-406": "Dojran",
  "MK-503": "Dolneni",
  "MK-804": "Gazi Baba",
  "MK-405": "Gevgelija",
  "MK-805": "Gjorče Petrov",
  "MK-604": "Gostivar",
  "MK-102": "Gradsko",
  "MK-807": "Ilinden",
  "MK-606": "Jegunovce",
  "MK-205": "Karbinci",
  "MK-808": "Karpoš",
  "MK-104": "Kavadarci",
  "MK-307": "Kičevo",
  "MK-809": "Kisela Voda",
  "MK-206": "Kočani",
  "MK-407": "Konče",
  "MK-701": "Kratovo",
  "MK-702": "Kriva Palanka",
  "MK-504": "Krivogaštani",
  "MK-505": "Kruševo",
  "MK-703": "Kumanovo",
  "MK-704": "Lipkovo",
  "MK-105": "Lozovo",
  "MK-207": "Makedonska Kamenica",
  "MK-308": "Makedonski Brod",
  "MK-607": "Mavrovo i Rostuše",
  "MK-506": "Mogila",
  "MK-106": "Negotino",
  "MK-507": "Novaci",
  "MK-408": "Novo Selo",
  "MK-310": "Ohrid",
  "MK-208": "Pehčevo",
  "MK-810": "Petrovec",
  "MK-311": "Plasnica",
  "MK-508": "Prilep",
  "MK-209": "Probištip",
  "MK-409": "Radoviš",
  "MK-705": "Rankovce",
  "MK-509": "Resen",
  "MK-107": "Rosoman",
  "MK-811": "Saraj",
  "MK-812": "Sopište",
  "MK-706": "Staro Nagoričane",
  "MK-312": "Struga",
  "MK-410": "Strumica",
  "MK-813": "Studeničani",
  "MK-108": "Sveti Nikole",
  "MK-211": "Štip",
  "MK-817": "Šuto Orizari",
  "MK-608": "Tearce",
  "MK-609": "Tetovo",
  "MK-403": "Valandovo",
  "MK-404": "Vasilevo",
  "MK-101": "Veles",
  "MK-301": "Vevčani",
  "MK-202": "Vinica",
  "MK-603": "Vrapčište",
  "MK-806": "Zelenikovo",
  "MK-204": "Zrnovci",
  "MK-605": "Želino",
  "NO-42": "Agder",
  "NO-34": "Innlandet",
  "NO-22": "Jan Mayen",
  "NO-15": "Møre og Romsdal",
  "NO-18": "Nordland",
  "NO-03": "Oslo",
  "NO-11": "Rogaland",
  "NO-21": "Svalbard",
  "NO-54": "Troms og Finnmarksefkv",
  "NO-50": "Trøndelagsma",
  "NO-38": "Vestfold og Telemark",
  "NO-46": "Vestland",
  "NO-30": "Viken",
  "PL-02": "Dolnośląskie",
  "PL-04": "Kujawsko-Pomorskie",
  "PL-06": "Lubelskie",
  "PL-08": "Lubuskie",
  "PL-10": "Łódzkie",
  "PL-12": "Małopolskie",
  "PL-14": "Mazowieckie",
  "PL-16": "Opolskie",
  "PL-18": "Podkarpackie",
  "PL-20": "Podlaskie",
  "PL-22": "Pomorskie",
  "PL-24": "Śląskie",
  "PL-26": "Świętokrzyskie",
  "PL-28": "Warmińsko-Mazurskie",
  "PL-30": "Wielkopolskie",
  "PL-32": "Zachodniopomorskie",
  "PT-01": "Aveiro",
  "PT-02": "Beja",
  "PT-03": "Braga",
  "PT-04": "Bragança",
  "PT-05": "Castelo Branco",
  "PT-06": "Coimbra",
  "PT-07": "Évora",
  "PT-08": "Faro",
  "PT-09": "Guarda",
  "PT-10": "Leiria",
  "PT-11": "Lisboa",
  "PT-12": "Portalegre",
  "PT-13": "Porto",
  "PT-30": "Região Autónoma da Madeira",
  "PT-20": "Região Autónoma dos Açores",
  "PT-14": "Santarém",
  "PT-15": "Setúbal",
  "PT-16": "Viana do Castelo",
  "PT-17": "Vila Real",
  "PT-18": "Viseu",
  "RO-AB": "Alba",
  "RO-AR": "Arad",
  "RO-AG": "Argeș",
  "RO-BC": "Bacău",
  "RO-BH": "Bihor",
  "RO-BN": "Bistrița-Năsăud",
  "RO-BT": "Botoșani",
  "RO-BV": "Brașov",
  "RO-BR": "Brăila",
  "RO-B": "București",
  "RO-BZ": "Buzău",
  "RO-CS": "Caraș-Severin",
  "RO-CL": "Călărași",
  "RO-CJ": "Cluj",
  "RO-CT": "Constanța",
  "RO-CV": "Covasna",
  "RO-DB": "Dâmbovița",
  "RO-DJ": "Dolj",
  "RO-GL": "Galați",
  "RO-GR": "Giurgiu",
  "RO-GJ": "Gorj",
  "RO-HR": "Harghita",
  "RO-HD": "Hunedoara",
  "RO-IL": "Ialomița",
  "RO-IS": "Iași",
  "RO-IF": "Ilfov",
  "RO-MM": "Maramureș",
  "RO-MH": "Mehedinți",
  "RO-MS": "Mureș",
  "RO-NT": "Neamț",
  "RO-OT": "Olt",
  "RO-PH": "Prahova",
  "RO-SM": "Satu Mare",
  "RO-SJ": "Sălaj",
  "RO-SB": "Sibiu",
  "RO-SV": "Suceava",
  "RO-TR": "Teleorman",
  "RO-TM": "Timiș",
  "RO-TL": "Tulcea",
  "RO-VS": "Vaslui",
  "RO-VL": "Vâlcea",
  "RO-VN": "Vrancea",
  "RU-AD": "Adygeya",
  "RU-AL": "Altay",
  "RU-ALT": "Altayskiy kray",
  "RU-AMU": "Amurskaya oblast'",
  "RU-ARK": "Arkhangel'skaya oblast'",
  "RU-AST": "Astrakhanskaya oblast'",
  "RU-BA": "Bashkortostan",
  "RU-BEL": "Belgorodskaya oblast'",
  "RU-BRY": "Bryanskaya oblast'",
  "RU-BU": "Buryatiya",
  "RU-CE": "Chechenskaya Respublika",
  "RU-CHE": "Chelyabinskaya oblast'",
  "RU-CHU": "Chukotskiy avtonomnyy okrug",
  "RU-CU": "Chuvashskaya Respublika",
  "RU-DA": "Dagestan",
  "RU-IN": "Ingushetiya",
  "RU-IRK": "Irkutskaya oblast'",
  "RU-IVA": "Ivanovskaya oblast'",
  "RU-KB": "Kabardino-BalkarskayaRespublika",
  "RU-KGD": "Kaliningradskaya oblast'",
  "RU-KL": "Kalmykiya",
  "RU-KLU": "Kaluzhskaya oblast'",
  "RU-KAM": "Kamchatskiy kray",
  "RU-KC": "Karachayevo-CherkesskayaRespublika",
  "RU-KR": "Kareliya",
  "RU-KEM": "Kemerovskaya oblast'",
  "RU-KHA": "Khabarovskiy kray",
  "RU-KK": "Khakasiya",
  "RU-KHM": "Khanty-Mansiyskiyavtonomnyy okrug",
  "RU-KIR": "Kirovskaya oblast'",
  "RU-KO": "Komi",
  "RU-KOS": "Kostromskaya oblast'",
  "RU-KDA": "Krasnodarskiy kray",
  "RU-KYA": "Krasnoyarskiy kray",
  "RU-KGN": "Kurganskaya oblast'",
  "RU-KRS": "Kurskaya oblast'",
  "RU-LEN": "Leningradskayaoblast'",
  "RU-LIP": "Lipetskaya oblast'",
  "RU-MAG": "Magadanskaya oblast'",
  "RU-ME": "Mariy El",
  "RU-MO": "Mordoviya",
  "RU-MOS": "Moskovskaya oblast'",
  "RU-MOW": "Moskva",
  "RU-MUR": "Murmanskaya oblast'",
  "RU-NEN": "Nenetskiyavtonomnyy okrug",
  "RU-NIZ": "Nizhegorodskaya oblast'",
  "RU-NGR": "Novgorodskaya oblast'",
  "RU-NVS": "Novosibirskayaoblast'",
  "RU-OMS": "Omskaya oblast'",
  "RU-ORE": "Orenburgskaya oblast'",
  "RU-ORL": "Orlovskaya oblast'",
  "RU-PNZ": "Penzenskaya oblast'",
  "RU-PER": "Permskiy kray",
  "RU-PRI": "Primorskiy kray",
  "RU-PSK": "Pskovskaya oblast'",
  "RU-ROS": "Rostovskaya oblast'",
  "RU-RYA": "Ryazanskaya oblast'",
  "RU-SA": "Saha",
  "RU-SAK": "Sakhalinskaya oblast'",
  "RU-SAM": "Samarskaya oblast'",
  "RU-SPE": "Sankt-Peterburg",
  "RU-SAR": "Saratovskaya oblast'",
  "RU-SE": "Severnaya Osetiya",
  "RU-SMO": "Smolenskaya oblast'",
  "RU-STA": "Stavropol'skiy kray",
  "RU-SVE": "Sverdlovskaya oblast'",
  "RU-TAM": "Tambovskaya oblast'",
  "RU-TA": "Tatarstan",
  "RU-TOM": "Tomskaya oblast'",
  "RU-TUL": "Tul'skaya oblast'",
  "RU-TVE": "Tverskaya oblast'",
  "RU-TYU": "Tyumenskaya oblast'",
  "RU-TY": "Tyva",
  "RU-UD": "Udmurtskaya Respublika",
  "RU-ULY": "Ul'yanovskaya oblast'",
  "RU-VLA": "Vladimirskayaoblast'",
  "RU-VGG": "Volgogradskayaoblast'",
  "RU-VLG": "Vologodskaya oblast'",
  "RU-VOR": "Voronezhskaya oblast'",
  "RU-YAN": "Yamalo-Nenetskiyavtonomnyy okrug",
  "RU-YAR": "Yaroslavskaya oblast'",
  "RU-YEV": "Yevreyskaya avtonomnaya oblast'",
  "RU-ZAB": "Zabaykal'skiy kray",
  "SM-01": "Acquaviva",
  "SM-06": "Borgo Maggiore",
  "SM-02": "Chiesanuova",
  "SM-07": "Città di San Marino",
  "SM-03": "Domagnano",
  "SM-04": "Faetano",
  "SM-05": "Fiorentino",
  "SM-08": "Montegiardino",
  "SM-09": "Serravalle",
  "SK-BC": "Banskobystrický kraj",
  "SK-BL": "Bratislavský kraj",
  "SK-KI": "Košický kraj",
  "SK-NI": "Nitriansky kraj",
  "SK-PV": "Prešovský kraj",
  "SK-TC": "Trenčiansky kraj",
  "SK-TA": "Trnavský kraj",
  "SK-ZI": "Žilinský kraj",
  "SI-001": "Ajdovščina",
  "SI-213": "Ankaran",
  "SI-195": "Apače",
  "SI-002": "Beltinci",
  "SI-148": "Benedikt",
  "SI-149": "Bistrica ob Sotli",
  "SI-003": "Bled",
  "SI-150": "Bloke",
  "SI-004": "Bohinj",
  "SI-005": "Borovnica",
  "SI-006": "Bovec",
  "SI-151": "Braslovče",
  "SI-007": "Brda",
  "SI-008": "Brezovica",
  "SI-009": "Brežice",
  "SI-152": "Cankova",
  "SI-011": "Celje",
  "SI-012": "Cerklje na Gorenjskem",
  "SI-013": "Cerknica",
  "SI-014": "Cerkno",
  "SI-153": "Cerkvenjak",
  "SI-196": "Cirkulane",
  "SI-015": "Črenšovci",
  "SI-016": "Črna na Koroškem",
  "SI-017": "Črnomelj",
  "SI-018": "Destrnik",
  "SI-019": "Divača",
  "SI-154": "Dobje",
  "SI-020": "Dobrepolje",
  "SI-155": "Dobrna",
  "SI-021": "Dobrova-Polhov Gradec",
  "SI-156": "Dobrovnik",
  "SI-022": "Dol pri Ljubljani",
  "SI-157": "Dolenjske Toplice",
  "SI-023": "Domžale",
  "SI-024": "Dornava",
  "SI-025": "Dravograd",
  "SI-026": "Duplek",
  "SI-027": "Gorenja vas-Poljane",
  "SI-028": "Gorišnica",
  "SI-207": "Gorje",
  "SI-029": "Gornja Radgona",
  "SI-030": "Gornji Grad",
  "SI-031": "Gornji Petrovci",
  "SI-158": "Grad",
  "SI-032": "Grosuplje",
  "SI-159": "Hajdina",
  "SI-160": "Hoče-Slivnica",
  "SI-161": "Hodoš",
  "SI-162": "Horjul",
  "SI-034": "Hrastnik",
  "SI-035": "Hrpelje-Kozina",
  "SI-036": "Idrija",
  "SI-037": "Ig",
  "SI-038": "Ilirska Bistrica",
  "SI-039": "Ivančna Gorica",
  "SI-040": "Izola",
  "SI-041": "Jesenice",
  "SI-163": "Jezersko",
  "SI-042": "Juršinci",
  "SI-043": "Kamnik",
  "SI-044": "Kanal ob Soči",
  "SI-045": "Kidričevo",
  "SI-046": "Kobarid",
  "SI-047": "Kobilje",
  "SI-048": "Kočevje",
  "SI-049": "Komen",
  "SI-164": "Komenda",
  "SI-050": "Koper",
  "SI-197": "Kostanjevica na Krki",
  "SI-165": "Kostel",
  "SI-051": "Kozje",
  "SI-052": "Kranj",
  "SI-053": "Kranjska Gora",
  "SI-166": "Križevci",
  "SI-054": "Krško",
  "SI-055": "Kungota",
  "SI-056": "Kuzma",
  "SI-057": "Laško",
  "SI-058": "Lenart",
  "SI-059": "Lendava",
  "SI-060": "Litija",
  "SI-061": "Ljubljana",
  "SI-062": "Ljubno",
  "SI-063": "Ljutomer",
  "SI-208": "Log-Dragomer",
  "SI-064": "Logatec",
  "SI-065": "Loška dolina",
  "SI-066": "Loški Potok",
  "SI-167": "Lovrenc na Pohorju",
  "SI-067": "Luče",
  "SI-068": "Lukovica",
  "SI-069": "Majšperk",
  "SI-198": "Makole",
  "SI-070": "Maribor",
  "SI-168": "Markovci",
  "SI-071": "Medvode",
  "SI-072": "Mengeš",
  "SI-073": "Metlika",
  "SI-074": "Mežica",
  "SI-169": "Miklavž na Dravskem polju",
  "SI-075": "Miren-Kostanjevica",
  "SI-212": "Mirna",
  "SI-170": "Mirna Peč",
  "SI-076": "Mislinja",
  "SI-199": "Mokronog-Trebelno",
  "SI-077": "Moravče",
  "SI-078": "Moravske Toplice",
  "SI-079": "Mozirje",
  "SI-080": "Murska Sobota",
  "SI-081": "Muta",
  "SI-082": "Naklo",
  "SI-083": "Nazarje",
  "SI-084": "Nova Gorica",
  "SI-085": "Novo Mesto",
  "SI-086": "Odranci",
  "SI-171": "Oplotnica",
  "SI-087": "Ormož",
  "SI-088": "Osilnica",
  "SI-089": "Pesnica",
  "SI-090": "Piran",
  "SI-091": "Pivka",
  "SI-092": "Podčetrtek",
  "SI-172": "Podlehnik",
  "SI-093": "Podvelka",
  "SI-200": "Poljčane",
  "SI-173": "Polzela",
  "SI-094": "Postojna",
  "SI-174": "Prebold",
  "SI-095": "Preddvor",
  "SI-175": "Prevalje",
  "SI-096": "Ptuj",
  "SI-097": "Puconci",
  "SI-098": "Rače-Fram",
  "SI-099": "Radeče",
  "SI-100": "Radenci",
  "SI-101": "Radlje ob Dravi",
  "SI-102": "Radovljica",
  "SI-103": "Ravne na Koroškem",
  "SI-176": "Razkrižje",
  "SI-209": "Rečica ob Savinji",
  "SI-201": "Renče-Vogrsko",
  "SI-104": "Ribnica",
  "SI-177": "Ribnica na Pohorju",
  "SI-106": "Rogaška Slatina",
  "SI-105": "Rogašovci",
  "SI-107": "Rogatec",
  "SI-108": "Ruše",
  "SI-178": "Selnica ob Dravi",
  "SI-109": "Semič",
  "SI-110": "Sevnica",
  "SI-111": "Sežana",
  "SI-112": "Slovenj Gradec",
  "SI-113": "Slovenska Bistrica",
  "SI-114": "Slovenske Konjice",
  "SI-179": "Sodražica",
  "SI-180": "Solčava",
  "SI-202": "Središče ob Dravi",
  "SI-115": "Starše",
  "SI-203": "Straža",
  "SI-181": "Sveta Ana",
  "SI-204": "Sveta Trojica v Slovenskih goricah",
  "SI-182": "Sveti Andraž v Slovenskih goricah",
  "SI-116": "Sveti Jurij ob Ščavnici",
  "SI-210": "Sveti Jurij v Slovenskih goricah",
  "SI-205": "Sveti Tomaž",
  "SI-033": "Šalovci",
  "SI-183": "Šempeter-Vrtojba",
  "SI-117": "Šenčur",
  "SI-118": "Šentilj",
  "SI-119": "Šentjernej",
  "SI-120": "Šentjur",
  "SI-211": "Šentrupert",
  "SI-121": "Škocjan",
  "SI-122": "Škofja Loka",
  "SI-123": "Škofljica",
  "SI-124": "Šmarje pri Jelšah",
  "SI-206": "Šmarješke Toplice",
  "SI-125": "Šmartno ob Paki",
  "SI-194": "Šmartno pri Litiji",
  "SI-126": "Šoštanj",
  "SI-127": "Štore",
  "SI-184": "Tabor",
  "SI-010": "Tišina",
  "SI-128": "Tolmin",
  "SI-129": "Trbovlje",
  "SI-130": "Trebnje",
  "SI-185": "Trnovska Vas",
  "SI-186": "Trzin",
  "SI-131": "Tržič",
  "SI-132": "Turnišče",
  "SI-133": "Velenje",
  "SI-187": "Velika Polana",
  "SI-134": "Velike Lašče",
  "SI-188": "Veržej",
  "SI-135": "Videm",
  "SI-136": "Vipava",
  "SI-137": "Vitanje",
  "SI-138": "Vodice",
  "SI-139": "Vojnik",
  "SI-189": "Vransko",
  "SI-140": "Vrhnika",
  "SI-141": "Vuzenica",
  "SI-142": "Zagorje ob Savi",
  "SI-143": "Zavrč",
  "SI-144": "Zreče",
  "SI-190": "Žalec",
  "SI-146": "Železniki",
  "SI-191": "Žetale",
  "SI-147": "Žiri",
  "SI-192": "Žirovnica",
  "SI-193": "Žužemberk",
  "ES-AN": "Andalucía",
  "ES-AR": "Aragón",
  "ES-AS": "Asturias",
  "ES-CN": "Canarias",
  "ES-CB": "Cantabria",
  "ES-CL": "Castilla y León",
  "ES-CM": "Castilla-La Mancha",
  "ES-CT": "Catalunya",
  "ES-CE": "Ceuta",
  "ES-EX": "Extremadura",
  "ES-GA": "Galicia",
  "ES-IB": "Illes Balears",
  "ES-RI": "La Rioja",
  "ES-MD": "Madrid",
  "ES-ML": "Melilla",
  "ES-MC": "Murcia",
  "ES-NC": "Navarra",
  "ES-PV": "País Vasco",
  "ES-VC": "Valenciana",
  "SE-K": "Blekinge län",
  "SE-W": "Dalarnas län",
  "SE-I": "Gotlands län",
  "SE-X": "Gävleborgs län",
  "SE-N": "Hallands län",
  "SE-Z": "Jämtlands län",
  "SE-F": "Jönköpings län",
  "SE-H": "Kalmar län",
  "SE-G": "Kronobergs län",
  "SE-BD": "Norrbottens län",
  "SE-M": "Skåne län",
  "SE-AB": "Stockholms län",
  "SE-D": "Södermanlands län",
  "SE-C": "Uppsala län",
  "SE-S": "Värmlands län",
  "SE-AC": "Västerbottens län",
  "SE-Y": "Västernorrlands län",
  "SE-U": "Västmanlands län",
  "SE-O": "Västra Götalands län",
  "SE-T": "Örebro län",
  "SE-E": "Östergötlands län",
  "CH-AG": "Aargau",
  "CH-AR": "Appenzell Ausserrhoden",
  "CH-AI": "Appenzell Innerrhoden",
  "CH-BL": "Basel-Landschaft",
  "CH-BS": "Basel-Stadt",
  "CH-BE": "Bern",
  "CH-FR": "Fribourg",
  "CH-GE": "Genève",
  "CH-GL": "Glarus",
  "CH-GR": "Graubünden",
  "CH-JU": "Jura",
  "CH-LU": "Luzern",
  "CH-NE": "Neuchâtel",
  "CH-NW": "Nidwalden",
  "CH-OW": "Obwalden",
  "CH-SG": "Sankt Gallen",
  "CH-SH": "Schaffhausen",
  "CH-SZ": "Schwyz",
  "CH-SO": "Solothurn",
  "CH-TG": "Thurgau",
  "CH-TI": "Ticino",
  "CH-UR": "Uri",
  "CH-VS": "Valais",
  "CH-VD": "Vaud",
  "CH-ZG": "Zug",
  "CH-ZH": "Zürich",
  "UA-43": "Avtonomna Respublika Krym",
  "UA-71": "Cherkaska oblast",
  "UA-74": "Chernihivska oblast",
  "UA-77": "Chernivetska oblast",
  "UA-12": "Dnipropetrovska oblast",
  "UA-14": "Donetska oblast",
  "UA-26": "Ivano-Frankivska oblast",
  "UA-63": "Kharkivska oblast",
  "UA-65": "Khersonska oblast",
  "UA-68": "Khmelnytska oblast",
  "UA-35": "Kirovohradska oblast",
  "UA-30": "Kyiv",
  "UA-32": "Kyivska oblast",
  "UA-09": "Luhanska oblast",
  "UA-46": "Lvivska oblast",
  "UA-48": "Mykolaivska oblast",
  "UA-51": "Odeska oblast",
  "UA-53": "Poltavska oblast",
  "UA-56": "Rivnenska oblast",
  "UA-40": "Sevastopol",
  "UA-59": "Sumska oblast",
  "UA-61": "Ternopilska oblast",
  "UA-05": "Vinnytska oblast",
  "UA-07": "Volynska oblast",
  "UA-21": "Zakarpatska oblast",
  "UA-23": "Zaporizka oblast",
  "UA-18": "Zhytomyrska oblast",
  "GB-ENG": "England",
  "GB-NIR": "Northern Ireland",
  "GB-SCT": "Scotland",
  "GB-WLS": "Wales",
  "ME-01": "Andrijevica",
  "ME-02": "Bar",
  "ME-03": "Berane",
  "ME-04": "Bijelo Polje",
  "ME-05": "Budva",
  "ME-06": "Cetinje",
  "ME-07": "Danilovgrad",
  "ME-22": "Gusinje",
  "ME-08": "Herceg-Novi",
  "ME-09": "Kolašin",
  "ME-10": "Kotor",
  "ME-11": "Mojkovac",
  "ME-12": "Nikšić",
  "ME-23": "Petnjica",
  "ME-13": "Plav",
  "ME-14": "Pljevlja",
  "ME-15": "Plužine",
  "ME-16": "Podgorica",
  "ME-17": "Rožaje",
  "ME-18": "Šavnik",
  "ME-19": "Tivat",
  "ME-24": "Tuzi",
  "ME-20": "Ulcinj",
  "ME-21": "Žabljak",
  "ME-25": "Zeta",
  "RS-KM": "Kosovo-Metohija[1]",
  "RS-VO": "Vojvodina",
};
