// ISO 3166-2 subdivisions for countries in North America (continent code: NA)
export const NORTH_AMERICA_REGIONS: Record<string, string> = {
  "AG-03": "Saint George",
  "AG-04": "Saint John",
  "AG-05": "Saint Mary",
  "AG-06": "Saint Paul",
  "AG-07": "Saint Peter",
  "AG-08": "Saint Philip",
  "AG-10": "Barbuda",
  "AG-11": "Redonda",
  "BS-AK": "Acklins",
  "BS-BY": "Berry Islands",
  "BS-BI": "Bimini",
  "BS-BP": "Black Point",
  "BS-CI": "Cat Island",
  "BS-CO": "Central Abaco",
  "BS-CS": "Central Andros",
  "BS-CE": "Central Eleuthera",
  "BS-FP": "City of Freeport",
  "BS-CK": "Crooked Island and Long Cay",
  "BS-EG": "East Grand Bahama",
  "BS-EX": "Exuma",
  "BS-GC": "Grand Cay",
  "BS-HI": "Harbour Island",
  "BS-HT": "Hope Town",
  "BS-IN": "Inagua",
  "BS-LI": "Long Island",
  "BS-MC": "Mangrove Cay",
  "BS-MG": "Mayaguana",
  "BS-MI": "Moore's Island",
  "BS-NP": "New Providence",
  "BS-NO": "North Abaco",
  "BS-NS": "North Andros",
  "BS-NE": "North Eleuthera",
  "BS-RI": "Ragged Island",
  "BS-RC": "Rum Cay",
  "BS-SS": "San Salvador",
  "BS-SO": "South Abaco",
  "BS-SA": "South Andros",
  "BS-SE": "South Eleuthera",
  "BS-SW": "Spanish Wells",
  "BS-WG": "West Grand Bahama",
  "BB-01": "Christ Church",
  "BB-02": "Saint Andrew",
  "BB-03": "Saint George",
  "BB-04": "Saint James",
  "BB-05": "Saint John",
  "BB-06": "Saint Joseph",
  "BB-07": "Saint Lucy",
  "BB-08": "Saint Michael",
  "BB-09": "Saint Peter",
  "BB-10": "Saint Philip",
  "BB-11": "Saint Thomas",
  "BZ-BZ": "Belize",
  "BZ-CY": "Cayo",
  "BZ-CZL": "Corozal",
  "BZ-OW": "Orange Walk",
  "BZ-SC": "Stann Creek",
  "BZ-TOL": "Toledo",
  "CA-AB": "Alberta",
  "CA-BC": "British Columbia",
  "CA-MB": "Manitoba",
  "CA-NB": "New Brunswick",
  "CA-NL": "Newfoundland and Labrador",
  "CA-NT": "Northwest Territories",
  "CA-NS": "Nova Scotia",
  "CA-NU": "Nunavut",
  "CA-ON": "Ontario",
  "CA-PE": "Prince Edward Island",
  "CA-QC": "Quebec",
  "CA-SK": "Saskatchewan",
  "CA-YT": "Yukon",
  "CR-A": "Alajuela",
  "CR-C": "Cartago",
  "CR-G": "Guanacaste",
  "CR-H": "Heredia",
  "CR-L": "Limón",
  "CR-P": "Puntarenas",
  "CR-SJ": "San José",
  "CU-15": "Artemisa",
  "CU-09": "Camagüey",
  "CU-08": "Ciego de Ávila",
  "CU-06": "Cienfuegos",
  "CU-12": "Granma",
  "CU-14": "Guantánamo",
  "CU-11": "Holguín",
  "CU-03": "La Habana",
  "CU-10": "Las Tunas",
  "CU-04": "Matanzas",
  "CU-16": "Mayabeque",
  "CU-01": "Pinar del Río",
  "CU-07": "Sancti Spíritus",
  "CU-13": "Santiago de Cuba",
  "CU-05": "Villa Clara",
  "CU-99": "Isla de la Juventud",
  "DM-02": "Saint Andrew",
  "DM-03": "Saint David",
  "DM-04": "Saint George",
  "DM-05": "Saint John",
  "DM-06": "Saint Joseph",
  "DM-07": "Saint Luke",
  "DM-08": "Saint Mark",
  "DM-09": "Saint Patrick",
  "DM-10": "Saint Paul",
  "DM-11": "Saint Peter",
  "DO-33": "Cibao Nordeste",
  "DO-34": "Cibao Noroeste",
  "DO-35": "Cibao Norte",
  "DO-36": "Cibao Sur",
  "DO-37": "El Valle",
  "DO-38": "Enriquillo",
  "DO-39": "Higuamo",
  "DO-40": "Ozama",
  "DO-41": "Valdesia",
  "DO-42": "Yuma",
  "SV-AH": "Ahuachapán",
  "SV-CA": "Cabañas",
  "SV-CH": "Chalatenango",
  "SV-CU": "Cuscatlán",
  "SV-LI": "La Libertad",
  "SV-PA": "La Paz",
  "SV-UN": "La Unión",
  "SV-MO": "Morazán",
  "SV-SM": "San Miguel",
  "SV-SS": "San Salvador",
  "SV-SV": "San Vicente",
  "SV-SA": "Santa Ana",
  "SV-SO": "Sonsonate",
  "SV-US": "Usulután",
  "GL-AV": "Avannaata Kommunia",
  "GL-KU": "Kommune Kujalleq",
  "GL-QT": "Kommune Qeqertalik",
  "GL-SM": "Kommuneqarfik Sermersooq",
  "GL-QE": "Qeqqata Kommunia",
  "GD-01": "Saint Andrew",
  "GD-02": "Saint David",
  "GD-03": "Saint George",
  "GD-04": "Saint John",
  "GD-05": "Saint Mark",
  "GD-06": "Saint Patrick",
  "GD-10": "Southern Grenadine Islands",
  "GT-16": "Alta Verapaz",
  "GT-15": "Baja Verapaz",
  "GT-04": "Chimaltenango",
  "GT-20": "Chiquimula",
  "GT-02": "El Progreso",
  "GT-05": "Escuintla",
  "GT-01": "Guatemala",
  "GT-13": "Huehuetenango",
  "GT-18": "Izabal",
  "GT-21": "Jalapa",
  "GT-22": "Jutiapa",
  "GT-17": "Petén",
  "GT-09": "Quetzaltenango",
  "GT-14": "Quiché",
  "GT-11": "Retalhuleu",
  "GT-03": "Sacatepéquez",
  "GT-12": "San Marcos",
  "GT-06": "Santa Rosa",
  "GT-07": "Sololá",
  "GT-10": "Suchitepéquez",
  "GT-08": "Totonicapán",
  "GT-19": "Zacapa",
  "HT-AR": "Artibonite",
  "HT-CE": "Centre",
  "HT-GA": "Grande’Anse",
  "HT-NI": "Nippes",
  "HT-ND": "Nord",
  "HT-NE": "Nord-Est",
  "HT-NO": "Nord-Ouest",
  "HT-OU": "Ouest",
  "HT-SD": "Sud",
  "HT-SE": "Sud-Est",
  "HN-AT": "Atlántida",
  "HN-CH": "Choluteca",
  "HN-CL": "Colón",
  "HN-CM": "Comayagua",
  "HN-CP": "Copán",
  "HN-CR": "Cortés",
  "HN-EP": "El Paraíso",
  "HN-FM": "Francisco Morazán",
  "HN-GD": "Gracias a Dios",
  "HN-IN": "Intibucá",
  "HN-IB": "Islas de la Bahía",
  "HN-LP": "La Paz",
  "HN-LE": "Lempira",
  "HN-OC": "Ocotepeque",
  "HN-OL": "Olancho",
  "HN-SB": "Santa Bárbara",
  "HN-VA": "Valle",
  "HN-YO": "Yoro",
  "JM-13": "Clarendon",
  "JM-09": "Hanover",
  "JM-01": "Kingston",
  "JM-12": "Manchester",
  "JM-04": "Portland",
  "JM-02": "Saint Andrew",
  "JM-06": "Saint Ann",
  "JM-14": "Saint Catherine",
  "JM-11": "Saint Elizabeth",
  "JM-08": "Saint James",
  "JM-05": "Saint Mary",
  "JM-03": "Saint Thomas",
  "JM-07": "Trelawny",
  "JM-10": "Westmoreland",
  "MX-AGU": "Aguascalientes",
  "MX-BCN": "Baja California",
  "MX-BCS": "Baja California Sur",
  "MX-CAM": "Campeche",
  "MX-CMX": "Ciudad de México",
  "MX-COA": "Coahuila de Zaragoza",
  "MX-COL": "Colima",
  "MX-CHP": "Chiapas",
  "MX-CHH": "Chihuahua",
  "MX-DUR": "Durango",
  "MX-GUA": "Guanajuato",
  "MX-GRO": "Guerrero",
  "MX-HID": "Hidalgo",
  "MX-JAL": "Jalisco",
  "MX-MEX": "México",
  "MX-MIC": "Michoacán de Ocampo",
  "MX-MOR": "Morelos",
  "MX-NAY": "Nayarit",
  "MX-NLE": "Nuevo León",
  "MX-OAX": "Oaxaca",
  "MX-PUE": "Puebla",
  "MX-QUE": "Querétaro",
  "MX-ROO": "Quintana Roo",
  "MX-SLP": "San Luis Potosí",
  "MX-SIN": "Sinaloa",
  "MX-SON": "Sonora",
  "MX-TAB": "Tabasco",
  "MX-TAM": "Tamaulipas",
  "MX-TLA": "Tlaxcala",
  "MX-VER": "Veracruz de Ignacio de la Llave",
  "MX-YUC": "Yucatán",
  "MX-ZAC": "Zacatecas",
  "NI-BO": "Boaco",
  "NI-CA": "Carazo",
  "NI-CI": "Chinandega",
  "NI-CO": "Chontales",
  "NI-AN": "Costa Caribe Norte",
  "NI-AS": "Costa Caribe Sur",
  "NI-ES": "Estelí",
  "NI-GR": "Granada",
  "NI-JI": "Jinotega",
  "NI-LE": "León",
  "NI-MD": "Madriz",
  "NI-MN": "Managua",
  "NI-MS": "Masaya",
  "NI-MT": "Matagalpa",
  "NI-NS": "Nueva Segovia",
  "NI-SJ": "Río San Juan",
  "NI-RI": "Rivas",
  "PA-1": "Bocas del Toro",
  "PA-4": "Chiriquí",
  "PA-2": "Coclé",
  "PA-3": "Colón",
  "PA-5": "Darién",
  "PA-EM": "Emberá",
  "PA-KY": "Guna Yala",
  "PA-6": "Herrera",
  "PA-7": "Los Santos",
  "PA-NT": "Naso Tjër Di",
  "PA-NB": "Ngäbe-Buglé",
  "PA-8": "Panamá",
  "PA-10": "Panamá Oeste",
  "PA-9": "Veraguas",
  "KN-K": "Saint Kitts",
  "KN-N": "Nevis",
  "LC-01": "Anse la Raye",
  "LC-12": "Canaries",
  "LC-02": "Castries",
  "LC-03": "Choiseul",
  "LC-05": "Dennery",
  "LC-06": "Gros Islet",
  "LC-07": "Laborie",
  "LC-08": "Micoud",
  "LC-10": "Soufrière",
  "LC-11": "Vieux Fort",
  "VC-01": "Charlotte",
  "VC-06": "Grenadines",
  "VC-02": "Saint Andrew",
  "VC-03": "Saint David",
  "VC-04": "Saint George",
  "VC-05": "Saint Patrick",
  "TT-ARI": "Arima",
  "TT-CHA": "Chaguanas",
  "TT-CTT": "Couva-Tabaquite-Talparo",
  "TT-DMN": "Diego Martin",
  "TT-MRC": "Mayaro-Rio Claro",
  "TT-PED": "Penal-Debe",
  "TT-POS": "Port of Spain",
  "TT-PRT": "Princes Town",
  "TT-PTF": "Point Fortin",
  "TT-SFO": "San Fernando",
  "TT-SGE": "Sangre Grande",
  "TT-SIP": "Siparia",
  "TT-SJL": "San Juan-Laventille",
  "TT-TOB": "Tobago",
  "TT-TUP": "Tunapuna-Piarco",
  "US-AL": "Alabama",
  "US-AK": "Alaska",
  "US-AZ": "Arizona",
  "US-AR": "Arkansas",
  "US-CA": "California",
  "US-CO": "Colorado",
  "US-CT": "Connecticut",
  "US-DE": "Delaware",
  "US-FL": "Florida",
  "US-GA": "Georgia",
  "US-HI": "Hawaii",
  "US-ID": "Idaho",
  "US-IL": "Illinois",
  "US-IN": "Indiana",
  "US-IA": "Iowa",
  "US-KS": "Kansas",
  "US-KY": "Kentucky",
  "US-LA": "Louisiana",
  "US-ME": "Maine",
  "US-MD": "Maryland",
  "US-MA": "Massachusetts",
  "US-MI": "Michigan",
  "US-MN": "Minnesota",
  "US-MS": "Mississippi",
  "US-MO": "Missouri",
  "US-MT": "Montana",
  "US-NE": "Nebraska",
  "US-NV": "Nevada",
  "US-NH": "New Hampshire",
  "US-NJ": "New Jersey",
  "US-NM": "New Mexico",
  "US-NY": "New York",
  "US-NC": "North Carolina",
  "US-ND": "North Dakota",
  "US-OH": "Ohio",
  "US-OK": "Oklahoma",
  "US-OR": "Oregon",
  "US-PA": "Pennsylvania",
  "US-RI": "Rhode Island",
  "US-SC": "South Carolina",
  "US-SD": "South Dakota",
  "US-TN": "Tennessee",
  "US-TX": "Texas",
  "US-UT": "Utah",
  "US-VT": "Vermont",
  "US-VA": "Virginia",
  "US-WA": "Washington",
  "US-WV": "West Virginia",
  "US-WI": "Wisconsin",
  "US-WY": "Wyoming",
  "US-DC": "District of Columbia",
  "US-AS": "American Samoa",
  "US-GU": "Guam",
  "US-MP": "Northern Mariana Islands",
  "US-PR": "Puerto Rico",
  "US-UM": "United States Minor Outlying Islands",
  "US-VI": "Virgin Islands",
  "BQ-BO": "Bonaire",
  "BQ-SA": "Saba",
  "BQ-SE": "Sint Eustatius",
};
