// ISO 3166-2 subdivisions for countries in Oceania (continent code: OC)
export const OCEANIA_REGIONS: Record<string, string> = {
  "AU-NSW": "New South Wales",
  "AU-QLD": "Queensland",
  "AU-SA": "South Australia",
  "AU-TAS": "Tasmania",
  "AU-VIC": "Victoria",
  "AU-WA": "Western Australia",
  "AU-ACT": "Australian Capital Territory",
  "AU-NT": "Northern Territory",
  "FJ-C": "Central",
  "FJ-E": "Eastern",
  "FJ-N": "Northern",
  "FJ-W": "Western",
  "FJ-R": "Rotuma",
  "KI-G": "Gilbert Islands",
  "KI-L": "Line Islands",
  "KI-P": "Phoenix Islands",
  "MH-L": "Ralik chain",
  "MH-T": "Ratak chain",
  "FM-TRK": "Chuuk",
  "FM-KSA": "Kosrae",
  "FM-PNI": "Pohnpei",
  "FM-YAP": "Yap",
  "NR-01": "Aiwo",
  "NR-02": "Anabar",
  "NR-03": "Anetan",
  "NR-04": "Anibare",
  "NR-05": "Baitsi",
  "NR-06": "Boe",
  "NR-07": "Buada",
  "NR-08": "Denigomodu",
  "NR-09": "Ewa",
  "NR-10": "Ijuw",
  "NR-11": "Meneng",
  "NR-12": "Nibok",
  "NR-13": "Uaboe",
  "NR-14": "Yaren",
  "NZ-AUK": "Auckland",
  "NZ-BOP": "Bay of Plenty",
  "NZ-CAN": "Canterbury",
  "NZ-CIT": "Chatham Islands Territory",
  "NZ-GIS": "Gisborne",
  "NZ-WGN": "Greater Wellington",
  "NZ-HKB": "Hawke's Bay",
  "NZ-MWT": "Manawatū-Whanganui",
  "NZ-MBH": "Marlborough",
  "NZ-NSN": "Nelson",
  "NZ-NTL": "Northland",
  "NZ-OTA": "Otago",
  "NZ-STL": "Southland",
  "NZ-TKI": "Taranaki",
  "NZ-TAS": "Tasman",
  "NZ-WKO": "Waikato",
  "NZ-WTC": "West Coast",
  "PW-002": "Aimeliik",
  "PW-004": "Airai",
  "PW-010": "Angaur",
  "PW-050": "Hatohobei",
  "PW-100": "Kayangel",
  "PW-150": "Koror",
  "PW-212": "Melekeok",
  "PW-214": "Ngaraard",
  "PW-218": "Ngarchelong",
  "PW-222": "Ngardmau",
  "PW-224": "Ngatpang",
  "PW-226": "Ngchesar",
  "PW-227": "Ngeremlengui",
  "PW-228": "Ngiwal",
  "PW-350": "Peleliu",
  "PW-370": "Sonsorol",
  "PG-NSB": "Bougainville",
  "PG-CPM": "Central",
  "PG-CPK": "Chimbu",
  "PG-EBR": "East New Britain",
  "PG-ESW": "East Sepik",
  "PG-EHG": "Eastern Highlands",
  "PG-EPW": "Enga",
  "PG-GPK": "Gulf",
  "PG-HLA": "Hela",
  "PG-JWK": "Jiwaka",
  "PG-MPM": "Madang",
  "PG-MRL": "Manus",
  "PG-MBA": "Milne Bay",
  "PG-MPL": "Morobe",
  "PG-NCD": "National Capital District",
  "PG-NIK": "New Ireland",
  "PG-NPP": "Northern",
  "PG-SHM": "Southern Highlands",
  "PG-WBK": "West New Britain",
  "PG-SAN": "West Sepik",
  "PG-WPD": "Western",
  "PG-WHM": "Western Highlands",
  "WS-AA": "A'ana",
  "WS-AL": "Aiga-i-le-Tai",
  "WS-AT": "Atua",
  "WS-FA": "Fa'asaleleaga",
  "WS-GE": "Gaga'emauga",
  "WS-GI": "Gagaifomauga",
  "WS-PA": "Palauli",
  "WS-SA": "Satupa'itea",
  "WS-TU": "Tuamasaga",
  "WS-VF": "Va'a-o-Fonoti",
  "WS-VS": "Vaisigano",
  "SB-CT": "Capital Territory",
  "SB-CE": "Central",
  "SB-CH": "Choiseul",
  "SB-GU": "Guadalcanal",
  "SB-IS": "Isabel",
  "SB-MK": "Makira-Ulawa",
  "SB-ML": "Malaita",
  "SB-RB": "Rennell and Bellona",
  "SB-TE": "Temotu",
  "SB-WE": "Western",
  "TO-01": "'Eua",
  "TO-02": "Ha'apai",
  "TO-03": "Niuas",
  "TO-04": "Tongatapu",
  "TO-05": "Vava'u",
  "TV-FUN": "Funafuti",
  "TV-NMG": "Nanumaga",
  "TV-NMA": "Nanumea",
  "TV-NIT": "Niutao",
  "TV-NUI": "Nui",
  "TV-NKF": "Nukufetau",
  "TV-NKL": "Nukulaelae",
  "TV-VAI": "Vaitupu",
  "UM-81": "Baker Island",
  "UM-84": "Howland Island",
  "UM-86": "Jarvis Island",
  "UM-67": "Johnston Atoll",
  "UM-89": "Kingman Reef",
  "UM-71": "Midway Islands",
  "UM-76": "Navassa Island",
  "UM-95": "Palmyra Atoll",
  "UM-79": "Wake Island",
  "VU-MAP": "Malampa",
  "VU-PAM": "Pénama",
  "VU-SAM": "Sanma",
  "VU-SEE": "Shéfa",
  "VU-TAE": "Taféa",
  "VU-TOB": "Torba",
  "WF-AL": "Alo",
  "WF-SG": "Sigave",
  "WF-UV": "Uvea",
};
