// ISO 3166-2 subdivisions for countries in South America (continent code: SA)
export const SOUTH_AMERICA_REGIONS: Record<string, string> = {
  "AR-B": "Buenos Aires",
  "AR-K": "Catamarca",
  "AR-H": "Chaco",
  "AR-U": "Chubut",
  "AR-C": "Ciudad Autónoma de Buenos Aires",
  "AR-X": "Córdoba",
  "AR-W": "Corrientes",
  "AR-E": "Entre Ríos",
  "AR-P": "Formosa",
  "AR-Y": "Jujuy",
  "AR-L": "La Pampa",
  "AR-F": "La Rioja",
  "AR-M": "Mendoza",
  "AR-N": "Misiones",
  "AR-Q": "Neuquén",
  "AR-R": "Río Negro",
  "AR-A": "Salta",
  "AR-J": "San Juan",
  "AR-D": "San Luis",
  "AR-Z": "Santa Cruz",
  "AR-S": "Santa Fe",
  "AR-G": "Santiago del Estero",
  "AR-V": "Tierra del Fuego",
  "AR-T": "Tucumán",
  "BO-C": "Cochabamba",
  "BO-H": "Chuquisaca",
  "BO-B": "El Beni",
  "BO-L": "La Paz",
  "BO-O": "Oruro",
  "BO-N": "Pando",
  "BO-P": "Potosí",
  "BO-S": "Santa Cruz",
  "BO-T": "Tarija",
  "BR-AC": "Acre",
  "BR-AL": "Alagoas",
  "BR-AP": "Amapá",
  "BR-AM": "Amazonas",
  "BR-BA": "Bahia",
  "BR-CE": "Ceará",
  "BR-DF": "Distrito Federal",
  "BR-ES": "Espírito Santo",
  "BR-GO": "Goiás",
  "BR-MA": "Maranhão",
  "BR-MT": "Mato Grosso",
  "BR-MS": "Mato Grosso do Sul",
  "BR-MG": "Minas Gerais",
  "BR-PA": "Pará",
  "BR-PB": "Paraíba",
  "BR-PR": "Paraná",
  "BR-PE": "Pernambuco",
  "BR-PI": "Piauí",
  "BR-RJ": "Rio de Janeiro",
  "BR-RN": "Rio Grande do Norte",
  "BR-RS": "Rio Grande do Sul",
  "BR-RO": "Rondônia",
  "BR-RR": "Roraima",
  "BR-SC": "Santa Catarina",
  "BR-SP": "São Paulo",
  "BR-SE": "Sergipe",
  "BR-TO": "Tocantins",
  "CL-AI": "Aisén del General Carlos Ibañez del Campo",
  "CL-AN": "Antofagasta",
  "CL-AP": "Arica y Parinacota",
  "CL-AT": "Atacama",
  "CL-BI": "Biobío",
  "CL-CO": "Coquimbo",
  "CL-AR": "La Araucanía",
  "CL-LI": "Libertador General Bernardo O'Higgins",
  "CL-LL": "Los Lagos",
  "CL-LR": "Los Ríos",
  "CL-MA": "Magallanes",
  "CL-ML": "Maule",
  "CL-NB": "Ñuble",
  "CL-RM": "Región Metropolitana de Santiago",
  "CL-TA": "Tarapacá",
  "CL-VS": "Valparaíso",
  "CO-AMA": "Amazonas",
  "CO-ANT": "Antioquia",
  "CO-ARA": "Arauca",
  "CO-ATL": "Atlántico",
  "CO-BOL": "Bolívar",
  "CO-BOY": "Boyacá",
  "CO-CAL": "Caldas",
  "CO-CAQ": "Caquetá",
  "CO-CAS": "Casanare",
  "CO-CAU": "Cauca",
  "CO-CES": "Cesar",
  "CO-COR": "Córdoba",
  "CO-CUN": "Cundinamarca",
  "CO-CHO": "Chocó",
  "CO-DC": "Distrito Capital de Bogotá",
  "CO-GUA": "Guainía",
  "CO-GUV": "Guaviare",
  "CO-HUI": "Huila",
  "CO-LAG": "La Guajira",
  "CO-MAG": "Magdalena",
  "CO-MET": "Meta",
  "CO-NAR": "Nariño",
  "CO-NSA": "Norte de Santander",
  "CO-PUT": "Putumayo",
  "CO-QUI": "Quindío",
  "CO-RIS": "Risaralda",
  "CO-SAP": "San Andrés",
  "CO-SAN": "Santander",
  "CO-SUC": "Sucre",
  "CO-TOL": "Tolima",
  "CO-VAC": "Valle del Cauca",
  "CO-VAU": "Vaupés",
  "CO-VID": "Vichada",
  "EC-A": "Azuay",
  "EC-B": "Bolívar",
  "EC-F": "Cañar",
  "EC-C": "Carchi",
  "EC-H": "Chimborazo",
  "EC-X": "Cotopaxi",
  "EC-O": "El Oro",
  "EC-E": "Esmeraldas",
  "EC-W": "Galápagos",
  "EC-G": "Guayas",
  "EC-I": "Imbabura",
  "EC-L": "Loja",
  "EC-R": "Los Ríos",
  "EC-M": "Manabí",
  "EC-S": "Morona Santiago",
  "EC-N": "Napo",
  "EC-D": "Orellana",
  "EC-Y": "Pastaza",
  "EC-P": "Pichincha",
  "EC-SE": "Santa Elena",
  "EC-SD": "Santo Domingo de los Tsáchilas",
  "EC-U": "Sucumbíos",
  "EC-T": "Tungurahua",
  "EC-Z": "Zamora Chinchipe",
  "GY-BA": "Barima-Waini",
  "GY-CU": "Cuyuni-Mazaruni",
  "GY-DE": "Demerara-Mahaica",
  "GY-EB": "East Berbice-Corentyne",
  "GY-ES": "Essequibo Islands-West Demerara",
  "GY-MA": "Mahaica-Berbice",
  "GY-PM": "Pomeroon-Supenaam",
  "GY-PT": "Potaro-Siparuni",
  "GY-UD": "Upper Demerara-Berbice",
  "GY-UT": "Upper Takutu-Upper Essequibo",
  "PY-16": "Alto Paraguay",
  "PY-10": "Alto Paraná",
  "PY-13": "Amambay",
  "PY-ASU": "Asunción",
  "PY-19": "Boquerón",
  "PY-5": "Caaguazú",
  "PY-6": "Caazapá",
  "PY-14": "Canindeyú",
  "PY-11": "Central",
  "PY-1": "Concepción",
  "PY-3": "Cordillera",
  "PY-4": "Guairá",
  "PY-7": "Itapúa",
  "PY-8": "Misiones",
  "PY-12": "Ñeembucú",
  "PY-9": "Paraguarí",
  "PY-15": "Presidente Hayes",
  "PY-2": "San Pedro",
  "PE-AMA": "Amazonas",
  "PE-ANC": "Ancash",
  "PE-APU": "Apurímac",
  "PE-ARE": "Arequipa",
  "PE-AYA": "Ayacucho",
  "PE-CAJ": "Cajamarca",
  "PE-CUS": "Cusco",
  "PE-CAL": "El Callao",
  "PE-HUV": "Huancavelica",
  "PE-HUC": "Huánuco",
  "PE-ICA": "Ica",
  "PE-JUN": "Junín",
  "PE-LAL": "La Libertad",
  "PE-LAM": "Lambayeque",
  "PE-LIM": "Lima",
  "PE-LOR": "Loreto",
  "PE-MDD": "Madre de Dios",
  "PE-MOQ": "Moquegua",
  "PE-LMA": "Municipalidad Metropolitana de Lima",
  "PE-PAS": "Pasco",
  "PE-PIU": "Piura",
  "PE-PUN": "Puno",
  "PE-SAM": "San Martín",
  "PE-TAC": "Tacna",
  "PE-TUM": "Tumbes",
  "PE-UCA": "Ucayali",
  "SR-BR": "Brokopondo",
  "SR-CM": "Commewijne",
  "SR-CR": "Coronie",
  "SR-MA": "Marowijne",
  "SR-NI": "Nickerie",
  "SR-PR": "Para",
  "SR-PM": "Paramaribo",
  "SR-SA": "Saramacca",
  "SR-SI": "Sipaliwini",
  "SR-WA": "Wanica",
  "UY-AR": "Artigas",
  "UY-CA": "Canelones",
  "UY-CL": "Cerro Largo",
  "UY-CO": "Colonia",
  "UY-DU": "Durazno",
  "UY-FS": "Flores",
  "UY-FD": "Florida",
  "UY-LA": "Lavalleja",
  "UY-MA": "Maldonado",
  "UY-MO": "Montevideo",
  "UY-PA": "Paysandú",
  "UY-RN": "Río Negro",
  "UY-RV": "Rivera",
  "UY-RO": "Rocha",
  "UY-SA": "Salto",
  "UY-SJ": "San José",
  "UY-SO": "Soriano",
  "UY-TA": "Tacuarembó",
  "UY-TT": "Treinta y Tres",
  "VE-Z": "Amazonas",
  "VE-B": "Anzoátegui",
  "VE-C": "Apure",
  "VE-D": "Aragua",
  "VE-E": "Barinas",
  "VE-F": "Bolívar",
  "VE-G": "Carabobo",
  "VE-H": "Cojedes",
  "VE-Y": "Delta Amacuro",
  "VE-W": "Dependencias Federales",
  "VE-A": "Distrito Capital",
  "VE-I": "Falcón",
  "VE-J": "Guárico",
  "VE-X": "La Guaira",
  "VE-K": "Lara",
  "VE-L": "Mérida",
  "VE-M": "Miranda",
  "VE-N": "Monagas",
  "VE-O": "Nueva Esparta",
  "VE-P": "Portuguesa",
  "VE-R": "Sucre",
  "VE-S": "Táchira",
  "VE-T": "Trujillo",
  "VE-U": "Yaracuy",
  "VE-V": "Zulia",
};
